// Code generated by internal/schema/generate.py; DO NOT EDIT.
package tmux

import (
	"context"
	"strconv"
)

type ClipboardMode string

const (
	ClipboardOff      ClipboardMode = "off"
	ClipboardOn       ClipboardMode = "on"
	ClipboardExternal ClipboardMode = "external"
)

func (v ClipboardMode) valid() bool {
	switch v {
	case ClipboardOff, ClipboardOn, ClipboardExternal:
		return true
	}
	return false
}

type StatusPosition string

const (
	StatusTop    StatusPosition = "top"
	StatusBottom StatusPosition = "bottom"
)

func (v StatusPosition) valid() bool {
	switch v {
	case StatusTop, StatusBottom:
		return true
	}
	return false
}

type StatusMode string

const (
	StatusOff        StatusMode = "off"
	StatusOn         StatusMode = "on"
	StatusTwoLines   StatusMode = "2"
	StatusThreeLines StatusMode = "3"
	StatusFourLines  StatusMode = "4"
	StatusFiveLines  StatusMode = "5"
)

func (v StatusMode) valid() bool {
	switch v {
	case StatusOff, StatusOn, StatusTwoLines, StatusThreeLines, StatusFourLines, StatusFiveLines:
		return true
	}
	return false
}

type DetachPolicy string

const (
	DetachOff        DetachPolicy = "off"
	DetachOn         DetachPolicy = "on"
	DetachNoDetached DetachPolicy = "no-detached"
	DetachPrevious   DetachPolicy = "previous"
	DetachNext       DetachPolicy = "next"
)

func (v DetachPolicy) valid() bool {
	switch v {
	case DetachOff, DetachOn, DetachNoDetached, DetachPrevious, DetachNext:
		return true
	}
	return false
}

type ModeKeys string

const (
	ModeKeysVi    ModeKeys = "vi"
	ModeKeysEmacs ModeKeys = "emacs"
)

func (v ModeKeys) valid() bool {
	switch v {
	case ModeKeysVi, ModeKeysEmacs:
		return true
	}
	return false
}

type WindowSizePolicy string

const (
	WindowSizeLargest  WindowSizePolicy = "largest"
	WindowSizeSmallest WindowSizePolicy = "smallest"
	WindowSizeManual   WindowSizePolicy = "manual"
	WindowSizeLatest   WindowSizePolicy = "latest"
)

func (v WindowSizePolicy) valid() bool {
	switch v {
	case WindowSizeLargest, WindowSizeSmallest, WindowSizeManual, WindowSizeLatest:
		return true
	}
	return false
}

type RemainOnExitPolicy string

const (
	RemainOff    RemainOnExitPolicy = "off"
	RemainOn     RemainOnExitPolicy = "on"
	RemainFailed RemainOnExitPolicy = "failed"
)

func (v RemainOnExitPolicy) valid() bool {
	switch v {
	case RemainOff, RemainOn, RemainFailed:
		return true
	}
	return false
}

type PaneBorderStatus string

const (
	BorderOff    PaneBorderStatus = "off"
	BorderTop    PaneBorderStatus = "top"
	BorderBottom PaneBorderStatus = "bottom"
)

func (v PaneBorderStatus) valid() bool {
	switch v {
	case BorderOff, BorderTop, BorderBottom:
		return true
	}
	return false
}

type PassthroughPolicy string

const (
	PassthroughOff PassthroughPolicy = "off"
	PassthroughOn  PassthroughPolicy = "on"
	PassthroughAll PassthroughPolicy = "all"
)

func (v PassthroughPolicy) valid() bool {
	switch v {
	case PassthroughOff, PassthroughOn, PassthroughAll:
		return true
	}
	return false
}
func (o ServerOptions) User(ctx context.Context, name string) (OptionValue[string], error) {
	return userGet(ctx, o.target, name)
}
func (o ServerOptions) SetUser(ctx context.Context, name, value string) error {
	return userSet(ctx, o.target, name, value, false)
}
func (o ServerOptions) UnsetUser(ctx context.Context, name string) error {
	return userSet(ctx, o.target, name, "", true)
}
func (o ServerOptions) Array(ctx context.Context, name string) ([]ArrayEntry, error) {
	return o.target.array(ctx, name)
}
func (o ServerOptions) UpdateArray(ctx context.Context, name string, updates []ArrayUpdate) (ArrayUpdateResult, error) {
	return o.target.updateArray(ctx, name, updates)
}

// EscapeTime observes escape-time; inherited origins may be unavailable.
func (o ServerOptions) EscapeTime(ctx context.Context) (OptionValue[int], error) {
	v, e := o.target.read(ctx, "escape-time")
	if e != nil {
		return OptionValue[int]{}, e
	}
	r, e := convertOption(v, parseOptionInt)
	if e != nil {
		return OptionValue[int]{}, afterError("EscapeTime", e)
	}
	return r, nil
}
func (o ServerOptions) SetEscapeTime(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SetEscapeTime", invalid("range"))
	}
	return o.target.set(ctx, "escape-time", strconv.Itoa(value), false)
}
func (o ServerOptions) UnsetEscapeTime(ctx context.Context) error {
	return o.target.set(ctx, "escape-time", "", true)
}

// BufferLimit observes buffer-limit; inherited origins may be unavailable.
func (o ServerOptions) BufferLimit(ctx context.Context) (OptionValue[int], error) {
	v, e := o.target.read(ctx, "buffer-limit")
	if e != nil {
		return OptionValue[int]{}, e
	}
	r, e := convertOption(v, parseOptionInt)
	if e != nil {
		return OptionValue[int]{}, afterError("BufferLimit", e)
	}
	return r, nil
}
func (o ServerOptions) SetBufferLimit(ctx context.Context, value int) error {
	if value < 1 || value > 2147483647 {
		return opError("SetBufferLimit", invalid("range"))
	}
	return o.target.set(ctx, "buffer-limit", strconv.Itoa(value), false)
}
func (o ServerOptions) UnsetBufferLimit(ctx context.Context) error {
	return o.target.set(ctx, "buffer-limit", "", true)
}

// ExitEmpty observes exit-empty; inherited origins may be unavailable.
func (o ServerOptions) ExitEmpty(ctx context.Context) (OptionValue[bool], error) {
	v, e := o.target.read(ctx, "exit-empty")
	if e != nil {
		return OptionValue[bool]{}, e
	}
	r, e := convertOption(v, parseOptionBool)
	if e != nil {
		return OptionValue[bool]{}, afterError("ExitEmpty", e)
	}
	return r, nil
}
func (o ServerOptions) SetExitEmpty(ctx context.Context, value bool) error {
	return o.target.set(ctx, "exit-empty", boolOption(value), false)
}
func (o ServerOptions) UnsetExitEmpty(ctx context.Context) error {
	return o.target.set(ctx, "exit-empty", "", true)
}

// ExitUnattached observes exit-unattached; inherited origins may be unavailable.
func (o ServerOptions) ExitUnattached(ctx context.Context) (OptionValue[bool], error) {
	v, e := o.target.read(ctx, "exit-unattached")
	if e != nil {
		return OptionValue[bool]{}, e
	}
	r, e := convertOption(v, parseOptionBool)
	if e != nil {
		return OptionValue[bool]{}, afterError("ExitUnattached", e)
	}
	return r, nil
}
func (o ServerOptions) SetExitUnattached(ctx context.Context, value bool) error {
	return o.target.set(ctx, "exit-unattached", boolOption(value), false)
}
func (o ServerOptions) UnsetExitUnattached(ctx context.Context) error {
	return o.target.set(ctx, "exit-unattached", "", true)
}

// DefaultTerminal observes default-terminal; inherited origins may be unavailable.
func (o ServerOptions) DefaultTerminal(ctx context.Context) (OptionValue[string], error) {
	v, e := o.target.read(ctx, "default-terminal")
	if e != nil {
		return OptionValue[string]{}, e
	}
	r, e := convertOption(v, func(s string) (string, error) { return s, nil })
	if e != nil {
		return OptionValue[string]{}, afterError("DefaultTerminal", e)
	}
	return r, nil
}
func (o ServerOptions) SetDefaultTerminal(ctx context.Context, value string) error {
	return o.target.set(ctx, "default-terminal", value, false)
}
func (o ServerOptions) UnsetDefaultTerminal(ctx context.Context) error {
	return o.target.set(ctx, "default-terminal", "", true)
}

// SetClipboard observes set-clipboard; inherited origins may be unavailable.
func (o ServerOptions) SetClipboard(ctx context.Context) (OptionValue[ClipboardMode], error) {
	v, e := o.target.read(ctx, "set-clipboard")
	if e != nil {
		return OptionValue[ClipboardMode]{}, e
	}
	r, e := convertOption(v, func(s string) (ClipboardMode, error) { return ClipboardMode(s), nil })
	if e != nil {
		return OptionValue[ClipboardMode]{}, afterError("SetClipboard", e)
	}
	return r, nil
}
func (o ServerOptions) SetSetClipboard(ctx context.Context, value ClipboardMode) error {
	if !value.valid() {
		return opError("SetSetClipboard", invalid("enum value"))
	}
	return o.target.set(ctx, "set-clipboard", string(value), false)
}
func (o ServerOptions) UnsetSetClipboard(ctx context.Context) error {
	return o.target.set(ctx, "set-clipboard", "", true)
}

// HistoryFile observes history-file; inherited origins may be unavailable.
func (o ServerOptions) HistoryFile(ctx context.Context) (OptionValue[string], error) {
	v, e := o.target.read(ctx, "history-file")
	if e != nil {
		return OptionValue[string]{}, e
	}
	r, e := convertOption(v, func(s string) (string, error) { return s, nil })
	if e != nil {
		return OptionValue[string]{}, afterError("HistoryFile", e)
	}
	return r, nil
}
func (o ServerOptions) SetHistoryFile(ctx context.Context, value string) error {
	return o.target.set(ctx, "history-file", value, false)
}
func (o ServerOptions) UnsetHistoryFile(ctx context.Context) error {
	return o.target.set(ctx, "history-file", "", true)
}
func (o SessionOptions) User(ctx context.Context, name string) (OptionValue[string], error) {
	return userGet(ctx, o.target, name)
}
func (o SessionOptions) SetUser(ctx context.Context, name, value string) error {
	return userSet(ctx, o.target, name, value, false)
}
func (o SessionOptions) UnsetUser(ctx context.Context, name string) error {
	return userSet(ctx, o.target, name, "", true)
}
func (o SessionOptions) Array(ctx context.Context, name string) ([]ArrayEntry, error) {
	return o.target.array(ctx, name)
}
func (o SessionOptions) UpdateArray(ctx context.Context, name string, updates []ArrayUpdate) (ArrayUpdateResult, error) {
	return o.target.updateArray(ctx, name, updates)
}

// HistoryLimit observes history-limit; inherited origins may be unavailable.
func (o SessionOptions) HistoryLimit(ctx context.Context) (OptionValue[int], error) {
	v, e := o.target.read(ctx, "history-limit")
	if e != nil {
		return OptionValue[int]{}, e
	}
	r, e := convertOption(v, parseOptionInt)
	if e != nil {
		return OptionValue[int]{}, afterError("HistoryLimit", e)
	}
	return r, nil
}
func (o SessionOptions) SetHistoryLimit(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SetHistoryLimit", invalid("range"))
	}
	return o.target.set(ctx, "history-limit", strconv.Itoa(value), false)
}
func (o SessionOptions) UnsetHistoryLimit(ctx context.Context) error {
	return o.target.set(ctx, "history-limit", "", true)
}

// BaseIndex observes base-index; inherited origins may be unavailable.
func (o SessionOptions) BaseIndex(ctx context.Context) (OptionValue[int], error) {
	v, e := o.target.read(ctx, "base-index")
	if e != nil {
		return OptionValue[int]{}, e
	}
	r, e := convertOption(v, parseOptionInt)
	if e != nil {
		return OptionValue[int]{}, afterError("BaseIndex", e)
	}
	return r, nil
}
func (o SessionOptions) SetBaseIndex(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SetBaseIndex", invalid("range"))
	}
	return o.target.set(ctx, "base-index", strconv.Itoa(value), false)
}
func (o SessionOptions) UnsetBaseIndex(ctx context.Context) error {
	return o.target.set(ctx, "base-index", "", true)
}

// DisplayTime observes display-time; inherited origins may be unavailable.
func (o SessionOptions) DisplayTime(ctx context.Context) (OptionValue[int], error) {
	v, e := o.target.read(ctx, "display-time")
	if e != nil {
		return OptionValue[int]{}, e
	}
	r, e := convertOption(v, parseOptionInt)
	if e != nil {
		return OptionValue[int]{}, afterError("DisplayTime", e)
	}
	return r, nil
}
func (o SessionOptions) SetDisplayTime(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SetDisplayTime", invalid("range"))
	}
	return o.target.set(ctx, "display-time", strconv.Itoa(value), false)
}
func (o SessionOptions) UnsetDisplayTime(ctx context.Context) error {
	return o.target.set(ctx, "display-time", "", true)
}

// RepeatTime observes repeat-time; inherited origins may be unavailable.
func (o SessionOptions) RepeatTime(ctx context.Context) (OptionValue[int], error) {
	v, e := o.target.read(ctx, "repeat-time")
	if e != nil {
		return OptionValue[int]{}, e
	}
	r, e := convertOption(v, parseOptionInt)
	if e != nil {
		return OptionValue[int]{}, afterError("RepeatTime", e)
	}
	return r, nil
}
func (o SessionOptions) SetRepeatTime(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SetRepeatTime", invalid("range"))
	}
	return o.target.set(ctx, "repeat-time", strconv.Itoa(value), false)
}
func (o SessionOptions) UnsetRepeatTime(ctx context.Context) error {
	return o.target.set(ctx, "repeat-time", "", true)
}

// Mouse observes mouse; inherited origins may be unavailable.
func (o SessionOptions) Mouse(ctx context.Context) (OptionValue[bool], error) {
	v, e := o.target.read(ctx, "mouse")
	if e != nil {
		return OptionValue[bool]{}, e
	}
	r, e := convertOption(v, parseOptionBool)
	if e != nil {
		return OptionValue[bool]{}, afterError("Mouse", e)
	}
	return r, nil
}
func (o SessionOptions) SetMouse(ctx context.Context, value bool) error {
	return o.target.set(ctx, "mouse", boolOption(value), false)
}
func (o SessionOptions) UnsetMouse(ctx context.Context) error {
	return o.target.set(ctx, "mouse", "", true)
}

// SetTitles observes set-titles; inherited origins may be unavailable.
func (o SessionOptions) SetTitles(ctx context.Context) (OptionValue[bool], error) {
	v, e := o.target.read(ctx, "set-titles")
	if e != nil {
		return OptionValue[bool]{}, e
	}
	r, e := convertOption(v, parseOptionBool)
	if e != nil {
		return OptionValue[bool]{}, afterError("SetTitles", e)
	}
	return r, nil
}
func (o SessionOptions) SetSetTitles(ctx context.Context, value bool) error {
	return o.target.set(ctx, "set-titles", boolOption(value), false)
}
func (o SessionOptions) UnsetSetTitles(ctx context.Context) error {
	return o.target.set(ctx, "set-titles", "", true)
}

// DefaultShell observes default-shell; inherited origins may be unavailable.
func (o SessionOptions) DefaultShell(ctx context.Context) (OptionValue[string], error) {
	v, e := o.target.read(ctx, "default-shell")
	if e != nil {
		return OptionValue[string]{}, e
	}
	r, e := convertOption(v, func(s string) (string, error) { return s, nil })
	if e != nil {
		return OptionValue[string]{}, afterError("DefaultShell", e)
	}
	return r, nil
}
func (o SessionOptions) SetDefaultShell(ctx context.Context, value string) error {
	return o.target.set(ctx, "default-shell", value, false)
}
func (o SessionOptions) UnsetDefaultShell(ctx context.Context) error {
	return o.target.set(ctx, "default-shell", "", true)
}

// DefaultCommand observes default-command; inherited origins may be unavailable.
func (o SessionOptions) DefaultCommand(ctx context.Context) (OptionValue[string], error) {
	v, e := o.target.read(ctx, "default-command")
	if e != nil {
		return OptionValue[string]{}, e
	}
	r, e := convertOption(v, func(s string) (string, error) { return s, nil })
	if e != nil {
		return OptionValue[string]{}, afterError("DefaultCommand", e)
	}
	return r, nil
}
func (o SessionOptions) SetDefaultCommand(ctx context.Context, value string) error {
	return o.target.set(ctx, "default-command", value, false)
}
func (o SessionOptions) UnsetDefaultCommand(ctx context.Context) error {
	return o.target.set(ctx, "default-command", "", true)
}

// DefaultSize observes default-size; inherited origins may be unavailable.
func (o SessionOptions) DefaultSize(ctx context.Context) (OptionValue[string], error) {
	v, e := o.target.read(ctx, "default-size")
	if e != nil {
		return OptionValue[string]{}, e
	}
	r, e := convertOption(v, func(s string) (string, error) { return s, nil })
	if e != nil {
		return OptionValue[string]{}, afterError("DefaultSize", e)
	}
	return r, nil
}
func (o SessionOptions) SetDefaultSize(ctx context.Context, value string) error {
	return o.target.set(ctx, "default-size", value, false)
}
func (o SessionOptions) UnsetDefaultSize(ctx context.Context) error {
	return o.target.set(ctx, "default-size", "", true)
}

// StatusLeft observes status-left; inherited origins may be unavailable.
func (o SessionOptions) StatusLeft(ctx context.Context) (OptionValue[string], error) {
	v, e := o.target.read(ctx, "status-left")
	if e != nil {
		return OptionValue[string]{}, e
	}
	r, e := convertOption(v, func(s string) (string, error) { return s, nil })
	if e != nil {
		return OptionValue[string]{}, afterError("StatusLeft", e)
	}
	return r, nil
}
func (o SessionOptions) SetStatusLeft(ctx context.Context, value string) error {
	return o.target.set(ctx, "status-left", value, false)
}
func (o SessionOptions) UnsetStatusLeft(ctx context.Context) error {
	return o.target.set(ctx, "status-left", "", true)
}

// StatusRight observes status-right; inherited origins may be unavailable.
func (o SessionOptions) StatusRight(ctx context.Context) (OptionValue[string], error) {
	v, e := o.target.read(ctx, "status-right")
	if e != nil {
		return OptionValue[string]{}, e
	}
	r, e := convertOption(v, func(s string) (string, error) { return s, nil })
	if e != nil {
		return OptionValue[string]{}, afterError("StatusRight", e)
	}
	return r, nil
}
func (o SessionOptions) SetStatusRight(ctx context.Context, value string) error {
	return o.target.set(ctx, "status-right", value, false)
}
func (o SessionOptions) UnsetStatusRight(ctx context.Context) error {
	return o.target.set(ctx, "status-right", "", true)
}

// StatusStyle observes status-style; inherited origins may be unavailable.
func (o SessionOptions) StatusStyle(ctx context.Context) (OptionValue[string], error) {
	v, e := o.target.read(ctx, "status-style")
	if e != nil {
		return OptionValue[string]{}, e
	}
	r, e := convertOption(v, func(s string) (string, error) { return s, nil })
	if e != nil {
		return OptionValue[string]{}, afterError("StatusStyle", e)
	}
	return r, nil
}
func (o SessionOptions) SetStatusStyle(ctx context.Context, value string) error {
	return o.target.set(ctx, "status-style", value, false)
}
func (o SessionOptions) UnsetStatusStyle(ctx context.Context) error {
	return o.target.set(ctx, "status-style", "", true)
}

// StatusPosition observes status-position; inherited origins may be unavailable.
func (o SessionOptions) StatusPosition(ctx context.Context) (OptionValue[StatusPosition], error) {
	v, e := o.target.read(ctx, "status-position")
	if e != nil {
		return OptionValue[StatusPosition]{}, e
	}
	r, e := convertOption(v, func(s string) (StatusPosition, error) { return StatusPosition(s), nil })
	if e != nil {
		return OptionValue[StatusPosition]{}, afterError("StatusPosition", e)
	}
	return r, nil
}
func (o SessionOptions) SetStatusPosition(ctx context.Context, value StatusPosition) error {
	if !value.valid() {
		return opError("SetStatusPosition", invalid("enum value"))
	}
	return o.target.set(ctx, "status-position", string(value), false)
}
func (o SessionOptions) UnsetStatusPosition(ctx context.Context) error {
	return o.target.set(ctx, "status-position", "", true)
}

// Status observes status; inherited origins may be unavailable.
func (o SessionOptions) Status(ctx context.Context) (OptionValue[StatusMode], error) {
	v, e := o.target.read(ctx, "status")
	if e != nil {
		return OptionValue[StatusMode]{}, e
	}
	r, e := convertOption(v, func(s string) (StatusMode, error) { return StatusMode(s), nil })
	if e != nil {
		return OptionValue[StatusMode]{}, afterError("Status", e)
	}
	return r, nil
}
func (o SessionOptions) SetStatus(ctx context.Context, value StatusMode) error {
	if !value.valid() {
		return opError("SetStatus", invalid("enum value"))
	}
	return o.target.set(ctx, "status", string(value), false)
}
func (o SessionOptions) UnsetStatus(ctx context.Context) error {
	return o.target.set(ctx, "status", "", true)
}

// Prefix observes prefix; inherited origins may be unavailable.
func (o SessionOptions) Prefix(ctx context.Context) (OptionValue[Key], error) {
	v, e := o.target.read(ctx, "prefix")
	if e != nil {
		return OptionValue[Key]{}, e
	}
	r, e := convertOption(v, func(s string) (Key, error) { return Key(s), nil })
	if e != nil {
		return OptionValue[Key]{}, afterError("Prefix", e)
	}
	return r, nil
}
func (o SessionOptions) SetPrefix(ctx context.Context, value Key) error {
	if !value.Valid() {
		return opError("SetPrefix", invalid("key value"))
	}
	return o.target.set(ctx, "prefix", string(value), false)
}
func (o SessionOptions) UnsetPrefix(ctx context.Context) error {
	return o.target.set(ctx, "prefix", "", true)
}

// DetachOnDestroy observes detach-on-destroy; inherited origins may be unavailable.
func (o SessionOptions) DetachOnDestroy(ctx context.Context) (OptionValue[DetachPolicy], error) {
	v, e := o.target.read(ctx, "detach-on-destroy")
	if e != nil {
		return OptionValue[DetachPolicy]{}, e
	}
	r, e := convertOption(v, func(s string) (DetachPolicy, error) { return DetachPolicy(s), nil })
	if e != nil {
		return OptionValue[DetachPolicy]{}, afterError("DetachOnDestroy", e)
	}
	return r, nil
}
func (o SessionOptions) SetDetachOnDestroy(ctx context.Context, value DetachPolicy) error {
	if !value.valid() {
		return opError("SetDetachOnDestroy", invalid("enum value"))
	}
	return o.target.set(ctx, "detach-on-destroy", string(value), false)
}
func (o SessionOptions) UnsetDetachOnDestroy(ctx context.Context) error {
	return o.target.set(ctx, "detach-on-destroy", "", true)
}
func (o WindowOptions) User(ctx context.Context, name string) (OptionValue[string], error) {
	return userGet(ctx, o.target, name)
}
func (o WindowOptions) SetUser(ctx context.Context, name, value string) error {
	return userSet(ctx, o.target, name, value, false)
}
func (o WindowOptions) UnsetUser(ctx context.Context, name string) error {
	return userSet(ctx, o.target, name, "", true)
}
func (o WindowOptions) Array(ctx context.Context, name string) ([]ArrayEntry, error) {
	return o.target.array(ctx, name)
}
func (o WindowOptions) UpdateArray(ctx context.Context, name string, updates []ArrayUpdate) (ArrayUpdateResult, error) {
	return o.target.updateArray(ctx, name, updates)
}

// AutomaticRename observes automatic-rename; inherited origins may be unavailable.
func (o WindowOptions) AutomaticRename(ctx context.Context) (OptionValue[bool], error) {
	v, e := o.target.read(ctx, "automatic-rename")
	if e != nil {
		return OptionValue[bool]{}, e
	}
	r, e := convertOption(v, parseOptionBool)
	if e != nil {
		return OptionValue[bool]{}, afterError("AutomaticRename", e)
	}
	return r, nil
}
func (o WindowOptions) SetAutomaticRename(ctx context.Context, value bool) error {
	return o.target.set(ctx, "automatic-rename", boolOption(value), false)
}
func (o WindowOptions) UnsetAutomaticRename(ctx context.Context) error {
	return o.target.set(ctx, "automatic-rename", "", true)
}

// AllowRename observes allow-rename; inherited origins may be unavailable.
func (o WindowOptions) AllowRename(ctx context.Context) (OptionValue[bool], error) {
	v, e := o.target.read(ctx, "allow-rename")
	if e != nil {
		return OptionValue[bool]{}, e
	}
	r, e := convertOption(v, parseOptionBool)
	if e != nil {
		return OptionValue[bool]{}, afterError("AllowRename", e)
	}
	return r, nil
}
func (o WindowOptions) SetAllowRename(ctx context.Context, value bool) error {
	return o.target.set(ctx, "allow-rename", boolOption(value), false)
}
func (o WindowOptions) UnsetAllowRename(ctx context.Context) error {
	return o.target.set(ctx, "allow-rename", "", true)
}

// AggressiveResize observes aggressive-resize; inherited origins may be unavailable.
func (o WindowOptions) AggressiveResize(ctx context.Context) (OptionValue[bool], error) {
	v, e := o.target.read(ctx, "aggressive-resize")
	if e != nil {
		return OptionValue[bool]{}, e
	}
	r, e := convertOption(v, parseOptionBool)
	if e != nil {
		return OptionValue[bool]{}, afterError("AggressiveResize", e)
	}
	return r, nil
}
func (o WindowOptions) SetAggressiveResize(ctx context.Context, value bool) error {
	return o.target.set(ctx, "aggressive-resize", boolOption(value), false)
}
func (o WindowOptions) UnsetAggressiveResize(ctx context.Context) error {
	return o.target.set(ctx, "aggressive-resize", "", true)
}

// PaneBaseIndex observes pane-base-index; inherited origins may be unavailable.
func (o WindowOptions) PaneBaseIndex(ctx context.Context) (OptionValue[int], error) {
	v, e := o.target.read(ctx, "pane-base-index")
	if e != nil {
		return OptionValue[int]{}, e
	}
	r, e := convertOption(v, parseOptionInt)
	if e != nil {
		return OptionValue[int]{}, afterError("PaneBaseIndex", e)
	}
	return r, nil
}
func (o WindowOptions) SetPaneBaseIndex(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SetPaneBaseIndex", invalid("range"))
	}
	return o.target.set(ctx, "pane-base-index", strconv.Itoa(value), false)
}
func (o WindowOptions) UnsetPaneBaseIndex(ctx context.Context) error {
	return o.target.set(ctx, "pane-base-index", "", true)
}

// ModeKeys observes mode-keys; inherited origins may be unavailable.
func (o WindowOptions) ModeKeys(ctx context.Context) (OptionValue[ModeKeys], error) {
	v, e := o.target.read(ctx, "mode-keys")
	if e != nil {
		return OptionValue[ModeKeys]{}, e
	}
	r, e := convertOption(v, func(s string) (ModeKeys, error) { return ModeKeys(s), nil })
	if e != nil {
		return OptionValue[ModeKeys]{}, afterError("ModeKeys", e)
	}
	return r, nil
}
func (o WindowOptions) SetModeKeys(ctx context.Context, value ModeKeys) error {
	if !value.valid() {
		return opError("SetModeKeys", invalid("enum value"))
	}
	return o.target.set(ctx, "mode-keys", string(value), false)
}
func (o WindowOptions) UnsetModeKeys(ctx context.Context) error {
	return o.target.set(ctx, "mode-keys", "", true)
}

// WindowSize observes window-size; inherited origins may be unavailable.
func (o WindowOptions) WindowSize(ctx context.Context) (OptionValue[WindowSizePolicy], error) {
	v, e := o.target.read(ctx, "window-size")
	if e != nil {
		return OptionValue[WindowSizePolicy]{}, e
	}
	r, e := convertOption(v, func(s string) (WindowSizePolicy, error) { return WindowSizePolicy(s), nil })
	if e != nil {
		return OptionValue[WindowSizePolicy]{}, afterError("WindowSize", e)
	}
	return r, nil
}
func (o WindowOptions) SetWindowSize(ctx context.Context, value WindowSizePolicy) error {
	if !value.valid() {
		return opError("SetWindowSize", invalid("enum value"))
	}
	return o.target.set(ctx, "window-size", string(value), false)
}
func (o WindowOptions) UnsetWindowSize(ctx context.Context) error {
	return o.target.set(ctx, "window-size", "", true)
}

// RemainOnExit observes remain-on-exit; inherited origins may be unavailable.
func (o WindowOptions) RemainOnExit(ctx context.Context) (OptionValue[RemainOnExitPolicy], error) {
	v, e := o.target.read(ctx, "remain-on-exit")
	if e != nil {
		return OptionValue[RemainOnExitPolicy]{}, e
	}
	r, e := convertOption(v, func(s string) (RemainOnExitPolicy, error) { return RemainOnExitPolicy(s), nil })
	if e != nil {
		return OptionValue[RemainOnExitPolicy]{}, afterError("RemainOnExit", e)
	}
	return r, nil
}
func (o WindowOptions) SetRemainOnExit(ctx context.Context, value RemainOnExitPolicy) error {
	if !value.valid() {
		return opError("SetRemainOnExit", invalid("enum value"))
	}
	return o.target.set(ctx, "remain-on-exit", string(value), false)
}
func (o WindowOptions) UnsetRemainOnExit(ctx context.Context) error {
	return o.target.set(ctx, "remain-on-exit", "", true)
}

// SynchronizePanes observes synchronize-panes; inherited origins may be unavailable.
func (o WindowOptions) SynchronizePanes(ctx context.Context) (OptionValue[bool], error) {
	v, e := o.target.read(ctx, "synchronize-panes")
	if e != nil {
		return OptionValue[bool]{}, e
	}
	r, e := convertOption(v, parseOptionBool)
	if e != nil {
		return OptionValue[bool]{}, afterError("SynchronizePanes", e)
	}
	return r, nil
}
func (o WindowOptions) SetSynchronizePanes(ctx context.Context, value bool) error {
	return o.target.set(ctx, "synchronize-panes", boolOption(value), false)
}
func (o WindowOptions) UnsetSynchronizePanes(ctx context.Context) error {
	return o.target.set(ctx, "synchronize-panes", "", true)
}

// PaneBorderStatus observes pane-border-status; inherited origins may be unavailable.
func (o WindowOptions) PaneBorderStatus(ctx context.Context) (OptionValue[PaneBorderStatus], error) {
	v, e := o.target.read(ctx, "pane-border-status")
	if e != nil {
		return OptionValue[PaneBorderStatus]{}, e
	}
	r, e := convertOption(v, func(s string) (PaneBorderStatus, error) { return PaneBorderStatus(s), nil })
	if e != nil {
		return OptionValue[PaneBorderStatus]{}, afterError("PaneBorderStatus", e)
	}
	return r, nil
}
func (o WindowOptions) SetPaneBorderStatus(ctx context.Context, value PaneBorderStatus) error {
	if !value.valid() {
		return opError("SetPaneBorderStatus", invalid("enum value"))
	}
	return o.target.set(ctx, "pane-border-status", string(value), false)
}
func (o WindowOptions) UnsetPaneBorderStatus(ctx context.Context) error {
	return o.target.set(ctx, "pane-border-status", "", true)
}

// PaneBorderFormat observes pane-border-format; inherited origins may be unavailable.
func (o WindowOptions) PaneBorderFormat(ctx context.Context) (OptionValue[string], error) {
	v, e := o.target.read(ctx, "pane-border-format")
	if e != nil {
		return OptionValue[string]{}, e
	}
	r, e := convertOption(v, func(s string) (string, error) { return s, nil })
	if e != nil {
		return OptionValue[string]{}, afterError("PaneBorderFormat", e)
	}
	return r, nil
}
func (o WindowOptions) SetPaneBorderFormat(ctx context.Context, value string) error {
	return o.target.set(ctx, "pane-border-format", value, false)
}
func (o WindowOptions) UnsetPaneBorderFormat(ctx context.Context) error {
	return o.target.set(ctx, "pane-border-format", "", true)
}

// ModeStyle observes mode-style; inherited origins may be unavailable.
func (o WindowOptions) ModeStyle(ctx context.Context) (OptionValue[string], error) {
	v, e := o.target.read(ctx, "mode-style")
	if e != nil {
		return OptionValue[string]{}, e
	}
	r, e := convertOption(v, func(s string) (string, error) { return s, nil })
	if e != nil {
		return OptionValue[string]{}, afterError("ModeStyle", e)
	}
	return r, nil
}
func (o WindowOptions) SetModeStyle(ctx context.Context, value string) error {
	return o.target.set(ctx, "mode-style", value, false)
}
func (o WindowOptions) UnsetModeStyle(ctx context.Context) error {
	return o.target.set(ctx, "mode-style", "", true)
}

// WindowStatusFormat observes window-status-format; inherited origins may be unavailable.
func (o WindowOptions) WindowStatusFormat(ctx context.Context) (OptionValue[string], error) {
	v, e := o.target.read(ctx, "window-status-format")
	if e != nil {
		return OptionValue[string]{}, e
	}
	r, e := convertOption(v, func(s string) (string, error) { return s, nil })
	if e != nil {
		return OptionValue[string]{}, afterError("WindowStatusFormat", e)
	}
	return r, nil
}
func (o WindowOptions) SetWindowStatusFormat(ctx context.Context, value string) error {
	return o.target.set(ctx, "window-status-format", value, false)
}
func (o WindowOptions) UnsetWindowStatusFormat(ctx context.Context) error {
	return o.target.set(ctx, "window-status-format", "", true)
}

// WindowStatusCurrentFormat observes window-status-current-format; inherited origins may be unavailable.
func (o WindowOptions) WindowStatusCurrentFormat(ctx context.Context) (OptionValue[string], error) {
	v, e := o.target.read(ctx, "window-status-current-format")
	if e != nil {
		return OptionValue[string]{}, e
	}
	r, e := convertOption(v, func(s string) (string, error) { return s, nil })
	if e != nil {
		return OptionValue[string]{}, afterError("WindowStatusCurrentFormat", e)
	}
	return r, nil
}
func (o WindowOptions) SetWindowStatusCurrentFormat(ctx context.Context, value string) error {
	return o.target.set(ctx, "window-status-current-format", value, false)
}
func (o WindowOptions) UnsetWindowStatusCurrentFormat(ctx context.Context) error {
	return o.target.set(ctx, "window-status-current-format", "", true)
}

// AllowPassthrough observes allow-passthrough; inherited origins may be unavailable.
func (o WindowOptions) AllowPassthrough(ctx context.Context) (OptionValue[PassthroughPolicy], error) {
	v, e := o.target.read(ctx, "allow-passthrough")
	if e != nil {
		return OptionValue[PassthroughPolicy]{}, e
	}
	r, e := convertOption(v, func(s string) (PassthroughPolicy, error) { return PassthroughPolicy(s), nil })
	if e != nil {
		return OptionValue[PassthroughPolicy]{}, afterError("AllowPassthrough", e)
	}
	return r, nil
}
func (o WindowOptions) SetAllowPassthrough(ctx context.Context, value PassthroughPolicy) error {
	if !value.valid() {
		return opError("SetAllowPassthrough", invalid("enum value"))
	}
	return o.target.set(ctx, "allow-passthrough", string(value), false)
}
func (o WindowOptions) UnsetAllowPassthrough(ctx context.Context) error {
	return o.target.set(ctx, "allow-passthrough", "", true)
}
func (o PaneOptions) User(ctx context.Context, name string) (OptionValue[string], error) {
	return userGet(ctx, o.target, name)
}
func (o PaneOptions) SetUser(ctx context.Context, name, value string) error {
	return userSet(ctx, o.target, name, value, false)
}
func (o PaneOptions) UnsetUser(ctx context.Context, name string) error {
	return userSet(ctx, o.target, name, "", true)
}
func (o PaneOptions) Array(ctx context.Context, name string) ([]ArrayEntry, error) {
	return o.target.array(ctx, name)
}
func (o PaneOptions) UpdateArray(ctx context.Context, name string, updates []ArrayUpdate) (ArrayUpdateResult, error) {
	return o.target.updateArray(ctx, name, updates)
}

// RemainOnExit observes remain-on-exit; inherited origins may be unavailable.
func (o PaneOptions) RemainOnExit(ctx context.Context) (OptionValue[RemainOnExitPolicy], error) {
	v, e := o.target.read(ctx, "remain-on-exit")
	if e != nil {
		return OptionValue[RemainOnExitPolicy]{}, e
	}
	r, e := convertOption(v, func(s string) (RemainOnExitPolicy, error) { return RemainOnExitPolicy(s), nil })
	if e != nil {
		return OptionValue[RemainOnExitPolicy]{}, afterError("RemainOnExit", e)
	}
	return r, nil
}
func (o PaneOptions) SetRemainOnExit(ctx context.Context, value RemainOnExitPolicy) error {
	if !value.valid() {
		return opError("SetRemainOnExit", invalid("enum value"))
	}
	return o.target.set(ctx, "remain-on-exit", string(value), false)
}
func (o PaneOptions) UnsetRemainOnExit(ctx context.Context) error {
	return o.target.set(ctx, "remain-on-exit", "", true)
}

// SynchronizePanes observes synchronize-panes; inherited origins may be unavailable.
func (o PaneOptions) SynchronizePanes(ctx context.Context) (OptionValue[bool], error) {
	v, e := o.target.read(ctx, "synchronize-panes")
	if e != nil {
		return OptionValue[bool]{}, e
	}
	r, e := convertOption(v, parseOptionBool)
	if e != nil {
		return OptionValue[bool]{}, afterError("SynchronizePanes", e)
	}
	return r, nil
}
func (o PaneOptions) SetSynchronizePanes(ctx context.Context, value bool) error {
	return o.target.set(ctx, "synchronize-panes", boolOption(value), false)
}
func (o PaneOptions) UnsetSynchronizePanes(ctx context.Context) error {
	return o.target.set(ctx, "synchronize-panes", "", true)
}

// AllowPassthrough observes allow-passthrough; inherited origins may be unavailable.
func (o PaneOptions) AllowPassthrough(ctx context.Context) (OptionValue[PassthroughPolicy], error) {
	v, e := o.target.read(ctx, "allow-passthrough")
	if e != nil {
		return OptionValue[PassthroughPolicy]{}, e
	}
	r, e := convertOption(v, func(s string) (PassthroughPolicy, error) { return PassthroughPolicy(s), nil })
	if e != nil {
		return OptionValue[PassthroughPolicy]{}, afterError("AllowPassthrough", e)
	}
	return r, nil
}
func (o PaneOptions) SetAllowPassthrough(ctx context.Context, value PassthroughPolicy) error {
	if !value.valid() {
		return opError("SetAllowPassthrough", invalid("enum value"))
	}
	return o.target.set(ctx, "allow-passthrough", string(value), false)
}
func (o PaneOptions) UnsetAllowPassthrough(ctx context.Context) error {
	return o.target.set(ctx, "allow-passthrough", "", true)
}

// AllowRename observes allow-rename; inherited origins may be unavailable.
func (o PaneOptions) AllowRename(ctx context.Context) (OptionValue[bool], error) {
	v, e := o.target.read(ctx, "allow-rename")
	if e != nil {
		return OptionValue[bool]{}, e
	}
	r, e := convertOption(v, parseOptionBool)
	if e != nil {
		return OptionValue[bool]{}, afterError("AllowRename", e)
	}
	return r, nil
}
func (o PaneOptions) SetAllowRename(ctx context.Context, value bool) error {
	return o.target.set(ctx, "allow-rename", boolOption(value), false)
}
func (o PaneOptions) UnsetAllowRename(ctx context.Context) error {
	return o.target.set(ctx, "allow-rename", "", true)
}

// ScrollOnClear observes scroll-on-clear; inherited origins may be unavailable.
func (o PaneOptions) ScrollOnClear(ctx context.Context) (OptionValue[bool], error) {
	v, e := o.target.read(ctx, "scroll-on-clear")
	if e != nil {
		return OptionValue[bool]{}, e
	}
	r, e := convertOption(v, parseOptionBool)
	if e != nil {
		return OptionValue[bool]{}, afterError("ScrollOnClear", e)
	}
	return r, nil
}
func (o PaneOptions) SetScrollOnClear(ctx context.Context, value bool) error {
	return o.target.set(ctx, "scroll-on-clear", boolOption(value), false)
}
func (o PaneOptions) UnsetScrollOnClear(ctx context.Context) error {
	return o.target.set(ctx, "scroll-on-clear", "", true)
}

// WindowStyle observes window-style; inherited origins may be unavailable.
func (o PaneOptions) WindowStyle(ctx context.Context) (OptionValue[string], error) {
	v, e := o.target.read(ctx, "window-style")
	if e != nil {
		return OptionValue[string]{}, e
	}
	r, e := convertOption(v, func(s string) (string, error) { return s, nil })
	if e != nil {
		return OptionValue[string]{}, afterError("WindowStyle", e)
	}
	return r, nil
}
func (o PaneOptions) SetWindowStyle(ctx context.Context, value string) error {
	return o.target.set(ctx, "window-style", value, false)
}
func (o PaneOptions) UnsetWindowStyle(ctx context.Context) error {
	return o.target.set(ctx, "window-style", "", true)
}

// WindowActiveStyle observes window-active-style; inherited origins may be unavailable.
func (o PaneOptions) WindowActiveStyle(ctx context.Context) (OptionValue[string], error) {
	v, e := o.target.read(ctx, "window-active-style")
	if e != nil {
		return OptionValue[string]{}, e
	}
	r, e := convertOption(v, func(s string) (string, error) { return s, nil })
	if e != nil {
		return OptionValue[string]{}, afterError("WindowActiveStyle", e)
	}
	return r, nil
}
func (o PaneOptions) SetWindowActiveStyle(ctx context.Context, value string) error {
	return o.target.set(ctx, "window-active-style", value, false)
}
func (o PaneOptions) UnsetWindowActiveStyle(ctx context.Context) error {
	return o.target.set(ctx, "window-active-style", "", true)
}
