#!/usr/bin/env python3
"""Generate scope-specific Go options from options.json; --check is read-only."""
import argparse
import json
from pathlib import Path
import subprocess
import sys

root = Path(__file__).resolve().parents[2]
data = json.loads((Path(__file__).parent / "options.json").read_text())
specs, enums = data["fields"], data["enums"]
generated=['// Code generated by internal/schema/generate.py; DO NOT EDIT.\npackage tmux\nimport("context";"strconv")\n']
for typ,choices in enums.items():
 generated.append('type '+typ+' string\nconst (\n'+''.join(f'{k} {typ} = {json.dumps(v)}\n' for k,v in choices.items())+')\n')
 generated.append(f'func (v {typ}) valid() bool {{switch v {{case '+','.join(choices)+':return true};return false}\n')
for cls,defs in specs.items():
 generated.append(f'func (o {cls}) User(ctx context.Context,name string)(OptionValue[string],error){{return userGet(ctx,o.target,name)}}\n')
 generated.append(f'func (o {cls}) SetUser(ctx context.Context,name,value string)error{{return userSet(ctx,o.target,name,value,false)}}\n')
 generated.append(f'func (o {cls}) UnsetUser(ctx context.Context,name string)error{{return userSet(ctx,o.target,name,"",true)}}\n')
 generated.append(f'func (o {cls}) Array(ctx context.Context,name string)([]ArrayEntry,error){{return o.target.array(ctx,name)}}\n')
 generated.append(f'func (o {cls}) UpdateArray(ctx context.Context,name string,updates []ArrayUpdate)(ArrayUpdateResult,error){{return o.target.updateArray(ctx,name,updates)}}\n')
 for method,key,typ,lo,hi in defs:
  parser={'int':'parseOptionInt','bool':'parseOptionBool','string':'func(s string)(string,error){return s,nil}'}.get(typ,f'func(s string)({typ},error){{return {typ}(s),nil}}')
  enc={'int':'strconv.Itoa(value)','bool':'boolOption(value)','string':'value'}.get(typ,'string(value)')
  validation=f'if value<{lo}||value>{hi}{{return opError("Set{method}",invalid("range"))}};' if typ=='int' else f'if !value.valid(){{return opError("Set{method}",invalid("enum value"))}};' if typ in enums else f'if !value.Valid(){{return opError("Set{method}",invalid("key value"))}};' if typ=='Key' else ''
  generated.append(f'// {method} observes {key}; inherited origins may be unavailable.\nfunc(o {cls}) {method}(ctx context.Context)(OptionValue[{typ}],error){{v,e:=o.target.read(ctx,"{key}");if e!=nil{{return OptionValue[{typ}]{{}},e}};r,e:=convertOption(v,{parser});if e!=nil{{return OptionValue[{typ}]{{}},afterError("{method}",e)}};return r,nil}}\n')
  generated.append(f'func(o {cls}) Set{method}(ctx context.Context,value {typ})error{{{validation}return o.target.set(ctx,"{key}",{enc},false)}}\n')
  generated.append(f'func(o {cls}) Unset{method}(ctx context.Context)error{{return o.target.set(ctx,"{key}","",true)}}\n')

source = "".join(generated).encode()
result = subprocess.run(["gofmt"], input=source, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True).stdout
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
path = root / "options_generated.go"
if args.check:
    if not path.exists() or path.read_bytes() != result:
        sys.exit("options_generated.go is stale; run python3 internal/schema/generate.py")
else:
    path.write_bytes(result)
