// Code generated by internal/schema/generate; DO NOT EDIT.

package tmux

import (
	"context"
	"strconv"
)

// ClipboardMode selects a supported tmux option value.
type ClipboardMode string

const (
	ClipboardExternal ClipboardMode = "external"
	ClipboardOff      ClipboardMode = "off"
	ClipboardOn       ClipboardMode = "on"
)

func (v ClipboardMode) valid() bool {
	switch v {
	case ClipboardExternal, ClipboardOff, ClipboardOn:
		return true
	}
	return false
}

// DetachPolicy selects a supported tmux option value.
type DetachPolicy string

const (
	DetachNext       DetachPolicy = "next"
	DetachNoDetached DetachPolicy = "no-detached"
	DetachOff        DetachPolicy = "off"
	DetachOn         DetachPolicy = "on"
	DetachPrevious   DetachPolicy = "previous"
)

func (v DetachPolicy) valid() bool {
	switch v {
	case DetachNext, DetachNoDetached, DetachOff, DetachOn, DetachPrevious:
		return true
	}
	return false
}

// ModeKeys selects a supported tmux option value.
type ModeKeys string

const (
	ModeKeysEmacs ModeKeys = "emacs"
	ModeKeysVi    ModeKeys = "vi"
)

func (v ModeKeys) valid() bool {
	switch v {
	case ModeKeysEmacs, ModeKeysVi:
		return true
	}
	return false
}

// PaneBorderStatus selects a supported tmux option value.
type PaneBorderStatus string

const (
	BorderBottom PaneBorderStatus = "bottom"
	BorderOff    PaneBorderStatus = "off"
	BorderTop    PaneBorderStatus = "top"
)

func (v PaneBorderStatus) valid() bool {
	switch v {
	case BorderBottom, BorderOff, BorderTop:
		return true
	}
	return false
}

// PassthroughPolicy selects a supported tmux option value.
type PassthroughPolicy string

const (
	PassthroughAll PassthroughPolicy = "all"
	PassthroughOff PassthroughPolicy = "off"
	PassthroughOn  PassthroughPolicy = "on"
)

func (v PassthroughPolicy) valid() bool {
	switch v {
	case PassthroughAll, PassthroughOff, PassthroughOn:
		return true
	}
	return false
}

// RemainOnExitPolicy selects a supported tmux option value.
type RemainOnExitPolicy string

const (
	RemainFailed RemainOnExitPolicy = "failed"
	RemainOff    RemainOnExitPolicy = "off"
	RemainOn     RemainOnExitPolicy = "on"
)

func (v RemainOnExitPolicy) valid() bool {
	switch v {
	case RemainFailed, RemainOff, RemainOn:
		return true
	}
	return false
}

// StatusMode selects a supported tmux option value.
type StatusMode string

const (
	StatusFiveLines  StatusMode = "5"
	StatusFourLines  StatusMode = "4"
	StatusOff        StatusMode = "off"
	StatusOn         StatusMode = "on"
	StatusThreeLines StatusMode = "3"
	StatusTwoLines   StatusMode = "2"
)

func (v StatusMode) valid() bool {
	switch v {
	case StatusFiveLines, StatusFourLines, StatusOff, StatusOn, StatusThreeLines, StatusTwoLines:
		return true
	}
	return false
}

// StatusPosition selects a supported tmux option value.
type StatusPosition string

const (
	StatusBottom StatusPosition = "bottom"
	StatusTop    StatusPosition = "top"
)

func (v StatusPosition) valid() bool {
	switch v {
	case StatusBottom, StatusTop:
		return true
	}
	return false
}

// WindowSizePolicy selects a supported tmux option value.
type WindowSizePolicy string

const (
	WindowSizeLargest  WindowSizePolicy = "largest"
	WindowSizeLatest   WindowSizePolicy = "latest"
	WindowSizeManual   WindowSizePolicy = "manual"
	WindowSizeSmallest WindowSizePolicy = "smallest"
)

func (v WindowSizePolicy) valid() bool {
	switch v {
	case WindowSizeLargest, WindowSizeLatest, WindowSizeManual, WindowSizeSmallest:
		return true
	}
	return false
}

// Get reads a scalar option by its tmux name, preserving local and effective values.
func (o PaneOptions) Get(ctx context.Context, name string) (OptionValue[string], error) {
	return o.target.read(ctx, name)
}

// Set sets a scalar option by its tmux name. Tmux validates the value.
func (o PaneOptions) Set(ctx context.Context, name, value string) error {
	return o.target.set(ctx, name, value, false)
}

// Unset removes the local value of an option by its tmux name.
func (o PaneOptions) Unset(ctx context.Context, name string) error {
	return o.target.set(ctx, name, "", true)
}

// User reads the value of a user-defined option (prefixed with @) in this scope.
func (o PaneOptions) User(ctx context.Context, name string) (OptionValue[string], error) {
	return userGet(ctx, o.target, name)
}

// SetUser sets the value of a user-defined option (prefixed with @) in this scope.
func (o PaneOptions) SetUser(ctx context.Context, name, value string) error {
	return userSet(ctx, o.target, name, value, false)
}

// UnsetUser removes a user-defined option (prefixed with @) from this scope.
func (o PaneOptions) UnsetUser(ctx context.Context, name string) error {
	return userSet(ctx, o.target, name, "", true)
}

// Array reads all index entries for the named array option in this scope.
func (o PaneOptions) Array(ctx context.Context, name string) ([]ArrayEntry, error) {
	return o.target.array(ctx, name)
}

// UpdateArray applies a batch of index updates and deletions to the named array option.
func (o PaneOptions) UpdateArray(ctx context.Context, name string, updates []ArrayUpdate) (ArrayUpdateResult, error) {
	return o.target.updateArray(ctx, name, updates)
}

// RemainOnExit observes remain-on-exit; inherited origins may be unavailable.
func (o PaneOptions) RemainOnExit(ctx context.Context) (OptionValue[RemainOnExitPolicy], error) {

	v, err := o.target.read(ctx, "remain-on-exit")
	if err != nil {
		return OptionValue[RemainOnExitPolicy]{}, err
	}
	r, err := convertOption(v, func(s string) (RemainOnExitPolicy, error) { return RemainOnExitPolicy(s), nil })
	if err != nil {
		return OptionValue[RemainOnExitPolicy]{}, afterError("RemainOnExit", err)
	}
	return r, nil

}

// SetRemainOnExit sets the remain-on-exit option in this scope.
func (o PaneOptions) SetRemainOnExit(ctx context.Context, value RemainOnExitPolicy) error {
	if !value.valid() {
		return opError("SetRemainOnExit", invalid("enum value"))
	}

	return o.target.set(ctx, "remain-on-exit", string(value), false)
}

// UnsetRemainOnExit unsets the remain-on-exit option in this scope, restoring inherited defaults.
func (o PaneOptions) UnsetRemainOnExit(ctx context.Context) error {
	return o.target.set(ctx, "remain-on-exit", "", true)
}

// SynchronizePanes observes synchronize-panes; inherited origins may be unavailable.
func (o PaneOptions) SynchronizePanes(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "synchronize-panes")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("SynchronizePanes", err)
	}
	return r, nil

}

// SetSynchronizePanes sets the synchronize-panes option in this scope.
func (o PaneOptions) SetSynchronizePanes(ctx context.Context, value bool) error {

	return o.target.set(ctx, "synchronize-panes", boolOption(value), false)
}

// UnsetSynchronizePanes unsets the synchronize-panes option in this scope, restoring inherited defaults.
func (o PaneOptions) UnsetSynchronizePanes(ctx context.Context) error {
	return o.target.set(ctx, "synchronize-panes", "", true)
}

// AllowPassthrough observes allow-passthrough; inherited origins may be unavailable.
func (o PaneOptions) AllowPassthrough(ctx context.Context) (OptionValue[PassthroughPolicy], error) {

	v, err := o.target.read(ctx, "allow-passthrough")
	if err != nil {
		return OptionValue[PassthroughPolicy]{}, err
	}
	r, err := convertOption(v, func(s string) (PassthroughPolicy, error) { return PassthroughPolicy(s), nil })
	if err != nil {
		return OptionValue[PassthroughPolicy]{}, afterError("AllowPassthrough", err)
	}
	return r, nil

}

// SetAllowPassthrough sets the allow-passthrough option in this scope.
func (o PaneOptions) SetAllowPassthrough(ctx context.Context, value PassthroughPolicy) error {
	if !value.valid() {
		return opError("SetAllowPassthrough", invalid("enum value"))
	}

	return o.target.set(ctx, "allow-passthrough", string(value), false)
}

// UnsetAllowPassthrough unsets the allow-passthrough option in this scope, restoring inherited defaults.
func (o PaneOptions) UnsetAllowPassthrough(ctx context.Context) error {
	return o.target.set(ctx, "allow-passthrough", "", true)
}

// AllowRename observes allow-rename; inherited origins may be unavailable.
func (o PaneOptions) AllowRename(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "allow-rename")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("AllowRename", err)
	}
	return r, nil

}

// SetAllowRename sets the allow-rename option in this scope.
func (o PaneOptions) SetAllowRename(ctx context.Context, value bool) error {

	return o.target.set(ctx, "allow-rename", boolOption(value), false)
}

// UnsetAllowRename unsets the allow-rename option in this scope, restoring inherited defaults.
func (o PaneOptions) UnsetAllowRename(ctx context.Context) error {
	return o.target.set(ctx, "allow-rename", "", true)
}

// ScrollOnClear observes scroll-on-clear; inherited origins may be unavailable.
func (o PaneOptions) ScrollOnClear(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "scroll-on-clear")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("ScrollOnClear", err)
	}
	return r, nil

}

// SetScrollOnClear sets the scroll-on-clear option in this scope.
func (o PaneOptions) SetScrollOnClear(ctx context.Context, value bool) error {

	return o.target.set(ctx, "scroll-on-clear", boolOption(value), false)
}

// UnsetScrollOnClear unsets the scroll-on-clear option in this scope, restoring inherited defaults.
func (o PaneOptions) UnsetScrollOnClear(ctx context.Context) error {
	return o.target.set(ctx, "scroll-on-clear", "", true)
}

// WindowStyle observes window-style; inherited origins may be unavailable.
func (o PaneOptions) WindowStyle(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "window-style")
}

// SetWindowStyle sets the window-style option in this scope.
func (o PaneOptions) SetWindowStyle(ctx context.Context, value string) error {

	return o.target.set(ctx, "window-style", value, false)
}

// UnsetWindowStyle unsets the window-style option in this scope, restoring inherited defaults.
func (o PaneOptions) UnsetWindowStyle(ctx context.Context) error {
	return o.target.set(ctx, "window-style", "", true)
}

// WindowActiveStyle observes window-active-style; inherited origins may be unavailable.
func (o PaneOptions) WindowActiveStyle(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "window-active-style")
}

// SetWindowActiveStyle sets the window-active-style option in this scope.
func (o PaneOptions) SetWindowActiveStyle(ctx context.Context, value string) error {

	return o.target.set(ctx, "window-active-style", value, false)
}

// UnsetWindowActiveStyle unsets the window-active-style option in this scope, restoring inherited defaults.
func (o PaneOptions) UnsetWindowActiveStyle(ctx context.Context) error {
	return o.target.set(ctx, "window-active-style", "", true)
}

// Get reads a scalar option by its tmux name, preserving local and effective values.
func (o ServerOptions) Get(ctx context.Context, name string) (OptionValue[string], error) {
	return o.target.read(ctx, name)
}

// Set sets a scalar option by its tmux name. Tmux validates the value.
func (o ServerOptions) Set(ctx context.Context, name, value string) error {
	return o.target.set(ctx, name, value, false)
}

// Unset removes the local value of an option by its tmux name.
func (o ServerOptions) Unset(ctx context.Context, name string) error {
	return o.target.set(ctx, name, "", true)
}

// User reads the value of a user-defined option (prefixed with @) in this scope.
func (o ServerOptions) User(ctx context.Context, name string) (OptionValue[string], error) {
	return userGet(ctx, o.target, name)
}

// SetUser sets the value of a user-defined option (prefixed with @) in this scope.
func (o ServerOptions) SetUser(ctx context.Context, name, value string) error {
	return userSet(ctx, o.target, name, value, false)
}

// UnsetUser removes a user-defined option (prefixed with @) from this scope.
func (o ServerOptions) UnsetUser(ctx context.Context, name string) error {
	return userSet(ctx, o.target, name, "", true)
}

// Array reads all index entries for the named array option in this scope.
func (o ServerOptions) Array(ctx context.Context, name string) ([]ArrayEntry, error) {
	return o.target.array(ctx, name)
}

// UpdateArray applies a batch of index updates and deletions to the named array option.
func (o ServerOptions) UpdateArray(ctx context.Context, name string, updates []ArrayUpdate) (ArrayUpdateResult, error) {
	return o.target.updateArray(ctx, name, updates)
}

// EscapeTime observes escape-time; inherited origins may be unavailable.
func (o ServerOptions) EscapeTime(ctx context.Context) (OptionValue[int], error) {

	v, err := o.target.read(ctx, "escape-time")
	if err != nil {
		return OptionValue[int]{}, err
	}
	r, err := convertOption(v, parseOptionInt)
	if err != nil {
		return OptionValue[int]{}, afterError("EscapeTime", err)
	}
	return r, nil

}

// SetEscapeTime sets the escape-time option in this scope.
func (o ServerOptions) SetEscapeTime(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SetEscapeTime", invalid("range"))
	}

	return o.target.set(ctx, "escape-time", strconv.Itoa(value), false)
}

// UnsetEscapeTime unsets the escape-time option in this scope, restoring inherited defaults.
func (o ServerOptions) UnsetEscapeTime(ctx context.Context) error {
	return o.target.set(ctx, "escape-time", "", true)
}

// BufferLimit observes buffer-limit; inherited origins may be unavailable.
func (o ServerOptions) BufferLimit(ctx context.Context) (OptionValue[int], error) {

	v, err := o.target.read(ctx, "buffer-limit")
	if err != nil {
		return OptionValue[int]{}, err
	}
	r, err := convertOption(v, parseOptionInt)
	if err != nil {
		return OptionValue[int]{}, afterError("BufferLimit", err)
	}
	return r, nil

}

// SetBufferLimit sets the buffer-limit option in this scope.
func (o ServerOptions) SetBufferLimit(ctx context.Context, value int) error {
	if value < 1 || value > 2147483647 {
		return opError("SetBufferLimit", invalid("range"))
	}

	return o.target.set(ctx, "buffer-limit", strconv.Itoa(value), false)
}

// UnsetBufferLimit unsets the buffer-limit option in this scope, restoring inherited defaults.
func (o ServerOptions) UnsetBufferLimit(ctx context.Context) error {
	return o.target.set(ctx, "buffer-limit", "", true)
}

// ExitEmpty observes exit-empty; inherited origins may be unavailable.
func (o ServerOptions) ExitEmpty(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "exit-empty")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("ExitEmpty", err)
	}
	return r, nil

}

// SetExitEmpty sets the exit-empty option in this scope.
func (o ServerOptions) SetExitEmpty(ctx context.Context, value bool) error {

	return o.target.set(ctx, "exit-empty", boolOption(value), false)
}

// UnsetExitEmpty unsets the exit-empty option in this scope, restoring inherited defaults.
func (o ServerOptions) UnsetExitEmpty(ctx context.Context) error {
	return o.target.set(ctx, "exit-empty", "", true)
}

// ExitUnattached observes exit-unattached; inherited origins may be unavailable.
func (o ServerOptions) ExitUnattached(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "exit-unattached")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("ExitUnattached", err)
	}
	return r, nil

}

// SetExitUnattached sets the exit-unattached option in this scope.
func (o ServerOptions) SetExitUnattached(ctx context.Context, value bool) error {

	return o.target.set(ctx, "exit-unattached", boolOption(value), false)
}

// UnsetExitUnattached unsets the exit-unattached option in this scope, restoring inherited defaults.
func (o ServerOptions) UnsetExitUnattached(ctx context.Context) error {
	return o.target.set(ctx, "exit-unattached", "", true)
}

// DefaultTerminal observes default-terminal; inherited origins may be unavailable.
func (o ServerOptions) DefaultTerminal(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "default-terminal")
}

// SetDefaultTerminal sets the default-terminal option in this scope.
func (o ServerOptions) SetDefaultTerminal(ctx context.Context, value string) error {

	return o.target.set(ctx, "default-terminal", value, false)
}

// UnsetDefaultTerminal unsets the default-terminal option in this scope, restoring inherited defaults.
func (o ServerOptions) UnsetDefaultTerminal(ctx context.Context) error {
	return o.target.set(ctx, "default-terminal", "", true)
}

// Clipboard observes set-clipboard; inherited origins may be unavailable.
func (o ServerOptions) Clipboard(ctx context.Context) (OptionValue[ClipboardMode], error) {

	v, err := o.target.read(ctx, "set-clipboard")
	if err != nil {
		return OptionValue[ClipboardMode]{}, err
	}
	r, err := convertOption(v, func(s string) (ClipboardMode, error) { return ClipboardMode(s), nil })
	if err != nil {
		return OptionValue[ClipboardMode]{}, afterError("Clipboard", err)
	}
	return r, nil

}

// SetClipboard sets the set-clipboard option in this scope.
func (o ServerOptions) SetClipboard(ctx context.Context, value ClipboardMode) error {
	if !value.valid() {
		return opError("SetClipboard", invalid("enum value"))
	}

	return o.target.set(ctx, "set-clipboard", string(value), false)
}

// UnsetClipboard unsets the set-clipboard option in this scope, restoring inherited defaults.
func (o ServerOptions) UnsetClipboard(ctx context.Context) error {
	return o.target.set(ctx, "set-clipboard", "", true)
}

// HistoryFile observes history-file; inherited origins may be unavailable.
func (o ServerOptions) HistoryFile(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "history-file")
}

// SetHistoryFile sets the history-file option in this scope.
func (o ServerOptions) SetHistoryFile(ctx context.Context, value string) error {

	return o.target.set(ctx, "history-file", value, false)
}

// UnsetHistoryFile unsets the history-file option in this scope, restoring inherited defaults.
func (o ServerOptions) UnsetHistoryFile(ctx context.Context) error {
	return o.target.set(ctx, "history-file", "", true)
}

// Get reads a scalar option by its tmux name, preserving local and effective values.
func (o SessionOptions) Get(ctx context.Context, name string) (OptionValue[string], error) {
	return o.target.read(ctx, name)
}

// Set sets a scalar option by its tmux name. Tmux validates the value.
func (o SessionOptions) Set(ctx context.Context, name, value string) error {
	return o.target.set(ctx, name, value, false)
}

// Unset removes the local value of an option by its tmux name.
func (o SessionOptions) Unset(ctx context.Context, name string) error {
	return o.target.set(ctx, name, "", true)
}

// User reads the value of a user-defined option (prefixed with @) in this scope.
func (o SessionOptions) User(ctx context.Context, name string) (OptionValue[string], error) {
	return userGet(ctx, o.target, name)
}

// SetUser sets the value of a user-defined option (prefixed with @) in this scope.
func (o SessionOptions) SetUser(ctx context.Context, name, value string) error {
	return userSet(ctx, o.target, name, value, false)
}

// UnsetUser removes a user-defined option (prefixed with @) from this scope.
func (o SessionOptions) UnsetUser(ctx context.Context, name string) error {
	return userSet(ctx, o.target, name, "", true)
}

// Array reads all index entries for the named array option in this scope.
func (o SessionOptions) Array(ctx context.Context, name string) ([]ArrayEntry, error) {
	return o.target.array(ctx, name)
}

// UpdateArray applies a batch of index updates and deletions to the named array option.
func (o SessionOptions) UpdateArray(ctx context.Context, name string, updates []ArrayUpdate) (ArrayUpdateResult, error) {
	return o.target.updateArray(ctx, name, updates)
}

// HistoryLimit observes history-limit; inherited origins may be unavailable.
func (o SessionOptions) HistoryLimit(ctx context.Context) (OptionValue[int], error) {

	v, err := o.target.read(ctx, "history-limit")
	if err != nil {
		return OptionValue[int]{}, err
	}
	r, err := convertOption(v, parseOptionInt)
	if err != nil {
		return OptionValue[int]{}, afterError("HistoryLimit", err)
	}
	return r, nil

}

// SetHistoryLimit sets the history-limit option in this scope.
func (o SessionOptions) SetHistoryLimit(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SetHistoryLimit", invalid("range"))
	}

	return o.target.set(ctx, "history-limit", strconv.Itoa(value), false)
}

// UnsetHistoryLimit unsets the history-limit option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetHistoryLimit(ctx context.Context) error {
	return o.target.set(ctx, "history-limit", "", true)
}

// BaseIndex observes base-index; inherited origins may be unavailable.
func (o SessionOptions) BaseIndex(ctx context.Context) (OptionValue[int], error) {

	v, err := o.target.read(ctx, "base-index")
	if err != nil {
		return OptionValue[int]{}, err
	}
	r, err := convertOption(v, parseOptionInt)
	if err != nil {
		return OptionValue[int]{}, afterError("BaseIndex", err)
	}
	return r, nil

}

// SetBaseIndex sets the base-index option in this scope.
func (o SessionOptions) SetBaseIndex(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SetBaseIndex", invalid("range"))
	}

	return o.target.set(ctx, "base-index", strconv.Itoa(value), false)
}

// UnsetBaseIndex unsets the base-index option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetBaseIndex(ctx context.Context) error {
	return o.target.set(ctx, "base-index", "", true)
}

// DisplayTime observes display-time; inherited origins may be unavailable.
func (o SessionOptions) DisplayTime(ctx context.Context) (OptionValue[int], error) {

	v, err := o.target.read(ctx, "display-time")
	if err != nil {
		return OptionValue[int]{}, err
	}
	r, err := convertOption(v, parseOptionInt)
	if err != nil {
		return OptionValue[int]{}, afterError("DisplayTime", err)
	}
	return r, nil

}

// SetDisplayTime sets the display-time option in this scope.
func (o SessionOptions) SetDisplayTime(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SetDisplayTime", invalid("range"))
	}

	return o.target.set(ctx, "display-time", strconv.Itoa(value), false)
}

// UnsetDisplayTime unsets the display-time option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetDisplayTime(ctx context.Context) error {
	return o.target.set(ctx, "display-time", "", true)
}

// RepeatTime observes repeat-time; inherited origins may be unavailable.
func (o SessionOptions) RepeatTime(ctx context.Context) (OptionValue[int], error) {

	v, err := o.target.read(ctx, "repeat-time")
	if err != nil {
		return OptionValue[int]{}, err
	}
	r, err := convertOption(v, parseOptionInt)
	if err != nil {
		return OptionValue[int]{}, afterError("RepeatTime", err)
	}
	return r, nil

}

// SetRepeatTime sets the repeat-time option in this scope.
func (o SessionOptions) SetRepeatTime(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SetRepeatTime", invalid("range"))
	}

	return o.target.set(ctx, "repeat-time", strconv.Itoa(value), false)
}

// UnsetRepeatTime unsets the repeat-time option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetRepeatTime(ctx context.Context) error {
	return o.target.set(ctx, "repeat-time", "", true)
}

// Mouse observes mouse; inherited origins may be unavailable.
func (o SessionOptions) Mouse(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "mouse")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("Mouse", err)
	}
	return r, nil

}

// SetMouse sets the mouse option in this scope.
func (o SessionOptions) SetMouse(ctx context.Context, value bool) error {

	return o.target.set(ctx, "mouse", boolOption(value), false)
}

// UnsetMouse unsets the mouse option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetMouse(ctx context.Context) error {
	return o.target.set(ctx, "mouse", "", true)
}

// Titles observes set-titles; inherited origins may be unavailable.
func (o SessionOptions) Titles(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "set-titles")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("Titles", err)
	}
	return r, nil

}

// SetTitles sets the set-titles option in this scope.
func (o SessionOptions) SetTitles(ctx context.Context, value bool) error {

	return o.target.set(ctx, "set-titles", boolOption(value), false)
}

// UnsetTitles unsets the set-titles option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetTitles(ctx context.Context) error {
	return o.target.set(ctx, "set-titles", "", true)
}

// DefaultShell observes default-shell; inherited origins may be unavailable.
func (o SessionOptions) DefaultShell(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "default-shell")
}

// SetDefaultShell sets the default-shell option in this scope.
func (o SessionOptions) SetDefaultShell(ctx context.Context, value string) error {

	return o.target.set(ctx, "default-shell", value, false)
}

// UnsetDefaultShell unsets the default-shell option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetDefaultShell(ctx context.Context) error {
	return o.target.set(ctx, "default-shell", "", true)
}

// DefaultCommand observes default-command; inherited origins may be unavailable.
func (o SessionOptions) DefaultCommand(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "default-command")
}

// SetDefaultCommand sets the default-command option in this scope.
func (o SessionOptions) SetDefaultCommand(ctx context.Context, value string) error {

	return o.target.set(ctx, "default-command", value, false)
}

// UnsetDefaultCommand unsets the default-command option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetDefaultCommand(ctx context.Context) error {
	return o.target.set(ctx, "default-command", "", true)
}

// DefaultSize observes default-size; inherited origins may be unavailable.
func (o SessionOptions) DefaultSize(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "default-size")
}

// SetDefaultSize sets the default-size option in this scope.
func (o SessionOptions) SetDefaultSize(ctx context.Context, value string) error {

	return o.target.set(ctx, "default-size", value, false)
}

// UnsetDefaultSize unsets the default-size option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetDefaultSize(ctx context.Context) error {
	return o.target.set(ctx, "default-size", "", true)
}

// StatusLeft observes status-left; inherited origins may be unavailable.
func (o SessionOptions) StatusLeft(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "status-left")
}

// SetStatusLeft sets the status-left option in this scope.
func (o SessionOptions) SetStatusLeft(ctx context.Context, value string) error {

	return o.target.set(ctx, "status-left", value, false)
}

// UnsetStatusLeft unsets the status-left option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetStatusLeft(ctx context.Context) error {
	return o.target.set(ctx, "status-left", "", true)
}

// StatusRight observes status-right; inherited origins may be unavailable.
func (o SessionOptions) StatusRight(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "status-right")
}

// SetStatusRight sets the status-right option in this scope.
func (o SessionOptions) SetStatusRight(ctx context.Context, value string) error {

	return o.target.set(ctx, "status-right", value, false)
}

// UnsetStatusRight unsets the status-right option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetStatusRight(ctx context.Context) error {
	return o.target.set(ctx, "status-right", "", true)
}

// StatusStyle observes status-style; inherited origins may be unavailable.
func (o SessionOptions) StatusStyle(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "status-style")
}

// SetStatusStyle sets the status-style option in this scope.
func (o SessionOptions) SetStatusStyle(ctx context.Context, value string) error {

	return o.target.set(ctx, "status-style", value, false)
}

// UnsetStatusStyle unsets the status-style option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetStatusStyle(ctx context.Context) error {
	return o.target.set(ctx, "status-style", "", true)
}

// StatusPosition observes status-position; inherited origins may be unavailable.
func (o SessionOptions) StatusPosition(ctx context.Context) (OptionValue[StatusPosition], error) {

	v, err := o.target.read(ctx, "status-position")
	if err != nil {
		return OptionValue[StatusPosition]{}, err
	}
	r, err := convertOption(v, func(s string) (StatusPosition, error) { return StatusPosition(s), nil })
	if err != nil {
		return OptionValue[StatusPosition]{}, afterError("StatusPosition", err)
	}
	return r, nil

}

// SetStatusPosition sets the status-position option in this scope.
func (o SessionOptions) SetStatusPosition(ctx context.Context, value StatusPosition) error {
	if !value.valid() {
		return opError("SetStatusPosition", invalid("enum value"))
	}

	return o.target.set(ctx, "status-position", string(value), false)
}

// UnsetStatusPosition unsets the status-position option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetStatusPosition(ctx context.Context) error {
	return o.target.set(ctx, "status-position", "", true)
}

// Status observes status; inherited origins may be unavailable.
func (o SessionOptions) Status(ctx context.Context) (OptionValue[StatusMode], error) {

	v, err := o.target.read(ctx, "status")
	if err != nil {
		return OptionValue[StatusMode]{}, err
	}
	r, err := convertOption(v, func(s string) (StatusMode, error) { return StatusMode(s), nil })
	if err != nil {
		return OptionValue[StatusMode]{}, afterError("Status", err)
	}
	return r, nil

}

// SetStatus sets the status option in this scope.
func (o SessionOptions) SetStatus(ctx context.Context, value StatusMode) error {
	if !value.valid() {
		return opError("SetStatus", invalid("enum value"))
	}

	return o.target.set(ctx, "status", string(value), false)
}

// UnsetStatus unsets the status option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetStatus(ctx context.Context) error {
	return o.target.set(ctx, "status", "", true)
}

// Prefix observes prefix; inherited origins may be unavailable.
func (o SessionOptions) Prefix(ctx context.Context) (OptionValue[Key], error) {

	v, err := o.target.read(ctx, "prefix")
	if err != nil {
		return OptionValue[Key]{}, err
	}
	r, err := convertOption(v, func(s string) (Key, error) { return Key(s), nil })
	if err != nil {
		return OptionValue[Key]{}, afterError("Prefix", err)
	}
	return r, nil

}

// SetPrefix sets the prefix option in this scope.
func (o SessionOptions) SetPrefix(ctx context.Context, value Key) error {
	if !value.Valid() {
		return opError("SetPrefix", invalid("key value"))
	}
	return o.target.set(ctx, "prefix", string(value), false)
}

// UnsetPrefix unsets the prefix option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetPrefix(ctx context.Context) error {
	return o.target.set(ctx, "prefix", "", true)
}

// DetachOnDestroy observes detach-on-destroy; inherited origins may be unavailable.
func (o SessionOptions) DetachOnDestroy(ctx context.Context) (OptionValue[DetachPolicy], error) {

	v, err := o.target.read(ctx, "detach-on-destroy")
	if err != nil {
		return OptionValue[DetachPolicy]{}, err
	}
	r, err := convertOption(v, func(s string) (DetachPolicy, error) { return DetachPolicy(s), nil })
	if err != nil {
		return OptionValue[DetachPolicy]{}, afterError("DetachOnDestroy", err)
	}
	return r, nil

}

// SetDetachOnDestroy sets the detach-on-destroy option in this scope.
func (o SessionOptions) SetDetachOnDestroy(ctx context.Context, value DetachPolicy) error {
	if !value.valid() {
		return opError("SetDetachOnDestroy", invalid("enum value"))
	}

	return o.target.set(ctx, "detach-on-destroy", string(value), false)
}

// UnsetDetachOnDestroy unsets the detach-on-destroy option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetDetachOnDestroy(ctx context.Context) error {
	return o.target.set(ctx, "detach-on-destroy", "", true)
}

// Get reads a scalar option by its tmux name, preserving local and effective values.
func (o WindowOptions) Get(ctx context.Context, name string) (OptionValue[string], error) {
	return o.target.read(ctx, name)
}

// Set sets a scalar option by its tmux name. Tmux validates the value.
func (o WindowOptions) Set(ctx context.Context, name, value string) error {
	return o.target.set(ctx, name, value, false)
}

// Unset removes the local value of an option by its tmux name.
func (o WindowOptions) Unset(ctx context.Context, name string) error {
	return o.target.set(ctx, name, "", true)
}

// User reads the value of a user-defined option (prefixed with @) in this scope.
func (o WindowOptions) User(ctx context.Context, name string) (OptionValue[string], error) {
	return userGet(ctx, o.target, name)
}

// SetUser sets the value of a user-defined option (prefixed with @) in this scope.
func (o WindowOptions) SetUser(ctx context.Context, name, value string) error {
	return userSet(ctx, o.target, name, value, false)
}

// UnsetUser removes a user-defined option (prefixed with @) from this scope.
func (o WindowOptions) UnsetUser(ctx context.Context, name string) error {
	return userSet(ctx, o.target, name, "", true)
}

// Array reads all index entries for the named array option in this scope.
func (o WindowOptions) Array(ctx context.Context, name string) ([]ArrayEntry, error) {
	return o.target.array(ctx, name)
}

// UpdateArray applies a batch of index updates and deletions to the named array option.
func (o WindowOptions) UpdateArray(ctx context.Context, name string, updates []ArrayUpdate) (ArrayUpdateResult, error) {
	return o.target.updateArray(ctx, name, updates)
}

// AutomaticRename observes automatic-rename; inherited origins may be unavailable.
func (o WindowOptions) AutomaticRename(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "automatic-rename")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("AutomaticRename", err)
	}
	return r, nil

}

// SetAutomaticRename sets the automatic-rename option in this scope.
func (o WindowOptions) SetAutomaticRename(ctx context.Context, value bool) error {

	return o.target.set(ctx, "automatic-rename", boolOption(value), false)
}

// UnsetAutomaticRename unsets the automatic-rename option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetAutomaticRename(ctx context.Context) error {
	return o.target.set(ctx, "automatic-rename", "", true)
}

// AllowRename observes allow-rename; inherited origins may be unavailable.
func (o WindowOptions) AllowRename(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "allow-rename")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("AllowRename", err)
	}
	return r, nil

}

// SetAllowRename sets the allow-rename option in this scope.
func (o WindowOptions) SetAllowRename(ctx context.Context, value bool) error {

	return o.target.set(ctx, "allow-rename", boolOption(value), false)
}

// UnsetAllowRename unsets the allow-rename option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetAllowRename(ctx context.Context) error {
	return o.target.set(ctx, "allow-rename", "", true)
}

// AggressiveResize observes aggressive-resize; inherited origins may be unavailable.
func (o WindowOptions) AggressiveResize(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "aggressive-resize")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("AggressiveResize", err)
	}
	return r, nil

}

// SetAggressiveResize sets the aggressive-resize option in this scope.
func (o WindowOptions) SetAggressiveResize(ctx context.Context, value bool) error {

	return o.target.set(ctx, "aggressive-resize", boolOption(value), false)
}

// UnsetAggressiveResize unsets the aggressive-resize option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetAggressiveResize(ctx context.Context) error {
	return o.target.set(ctx, "aggressive-resize", "", true)
}

// PaneBaseIndex observes pane-base-index; inherited origins may be unavailable.
func (o WindowOptions) PaneBaseIndex(ctx context.Context) (OptionValue[int], error) {

	v, err := o.target.read(ctx, "pane-base-index")
	if err != nil {
		return OptionValue[int]{}, err
	}
	r, err := convertOption(v, parseOptionInt)
	if err != nil {
		return OptionValue[int]{}, afterError("PaneBaseIndex", err)
	}
	return r, nil

}

// SetPaneBaseIndex sets the pane-base-index option in this scope.
func (o WindowOptions) SetPaneBaseIndex(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SetPaneBaseIndex", invalid("range"))
	}

	return o.target.set(ctx, "pane-base-index", strconv.Itoa(value), false)
}

// UnsetPaneBaseIndex unsets the pane-base-index option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetPaneBaseIndex(ctx context.Context) error {
	return o.target.set(ctx, "pane-base-index", "", true)
}

// ModeKeys observes mode-keys; inherited origins may be unavailable.
func (o WindowOptions) ModeKeys(ctx context.Context) (OptionValue[ModeKeys], error) {

	v, err := o.target.read(ctx, "mode-keys")
	if err != nil {
		return OptionValue[ModeKeys]{}, err
	}
	r, err := convertOption(v, func(s string) (ModeKeys, error) { return ModeKeys(s), nil })
	if err != nil {
		return OptionValue[ModeKeys]{}, afterError("ModeKeys", err)
	}
	return r, nil

}

// SetModeKeys sets the mode-keys option in this scope.
func (o WindowOptions) SetModeKeys(ctx context.Context, value ModeKeys) error {
	if !value.valid() {
		return opError("SetModeKeys", invalid("enum value"))
	}

	return o.target.set(ctx, "mode-keys", string(value), false)
}

// UnsetModeKeys unsets the mode-keys option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetModeKeys(ctx context.Context) error {
	return o.target.set(ctx, "mode-keys", "", true)
}

// WindowSize observes window-size; inherited origins may be unavailable.
func (o WindowOptions) WindowSize(ctx context.Context) (OptionValue[WindowSizePolicy], error) {

	v, err := o.target.read(ctx, "window-size")
	if err != nil {
		return OptionValue[WindowSizePolicy]{}, err
	}
	r, err := convertOption(v, func(s string) (WindowSizePolicy, error) { return WindowSizePolicy(s), nil })
	if err != nil {
		return OptionValue[WindowSizePolicy]{}, afterError("WindowSize", err)
	}
	return r, nil

}

// SetWindowSize sets the window-size option in this scope.
func (o WindowOptions) SetWindowSize(ctx context.Context, value WindowSizePolicy) error {
	if !value.valid() {
		return opError("SetWindowSize", invalid("enum value"))
	}

	return o.target.set(ctx, "window-size", string(value), false)
}

// UnsetWindowSize unsets the window-size option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetWindowSize(ctx context.Context) error {
	return o.target.set(ctx, "window-size", "", true)
}

// RemainOnExit observes remain-on-exit; inherited origins may be unavailable.
func (o WindowOptions) RemainOnExit(ctx context.Context) (OptionValue[RemainOnExitPolicy], error) {

	v, err := o.target.read(ctx, "remain-on-exit")
	if err != nil {
		return OptionValue[RemainOnExitPolicy]{}, err
	}
	r, err := convertOption(v, func(s string) (RemainOnExitPolicy, error) { return RemainOnExitPolicy(s), nil })
	if err != nil {
		return OptionValue[RemainOnExitPolicy]{}, afterError("RemainOnExit", err)
	}
	return r, nil

}

// SetRemainOnExit sets the remain-on-exit option in this scope.
func (o WindowOptions) SetRemainOnExit(ctx context.Context, value RemainOnExitPolicy) error {
	if !value.valid() {
		return opError("SetRemainOnExit", invalid("enum value"))
	}

	return o.target.set(ctx, "remain-on-exit", string(value), false)
}

// UnsetRemainOnExit unsets the remain-on-exit option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetRemainOnExit(ctx context.Context) error {
	return o.target.set(ctx, "remain-on-exit", "", true)
}

// SynchronizePanes observes synchronize-panes; inherited origins may be unavailable.
func (o WindowOptions) SynchronizePanes(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "synchronize-panes")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("SynchronizePanes", err)
	}
	return r, nil

}

// SetSynchronizePanes sets the synchronize-panes option in this scope.
func (o WindowOptions) SetSynchronizePanes(ctx context.Context, value bool) error {

	return o.target.set(ctx, "synchronize-panes", boolOption(value), false)
}

// UnsetSynchronizePanes unsets the synchronize-panes option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetSynchronizePanes(ctx context.Context) error {
	return o.target.set(ctx, "synchronize-panes", "", true)
}

// PaneBorderStatus observes pane-border-status; inherited origins may be unavailable.
func (o WindowOptions) PaneBorderStatus(ctx context.Context) (OptionValue[PaneBorderStatus], error) {

	v, err := o.target.read(ctx, "pane-border-status")
	if err != nil {
		return OptionValue[PaneBorderStatus]{}, err
	}
	r, err := convertOption(v, func(s string) (PaneBorderStatus, error) { return PaneBorderStatus(s), nil })
	if err != nil {
		return OptionValue[PaneBorderStatus]{}, afterError("PaneBorderStatus", err)
	}
	return r, nil

}

// SetPaneBorderStatus sets the pane-border-status option in this scope.
func (o WindowOptions) SetPaneBorderStatus(ctx context.Context, value PaneBorderStatus) error {
	if !value.valid() {
		return opError("SetPaneBorderStatus", invalid("enum value"))
	}

	return o.target.set(ctx, "pane-border-status", string(value), false)
}

// UnsetPaneBorderStatus unsets the pane-border-status option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetPaneBorderStatus(ctx context.Context) error {
	return o.target.set(ctx, "pane-border-status", "", true)
}

// PaneBorderFormat observes pane-border-format; inherited origins may be unavailable.
func (o WindowOptions) PaneBorderFormat(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "pane-border-format")
}

// SetPaneBorderFormat sets the pane-border-format option in this scope.
func (o WindowOptions) SetPaneBorderFormat(ctx context.Context, value string) error {

	return o.target.set(ctx, "pane-border-format", value, false)
}

// UnsetPaneBorderFormat unsets the pane-border-format option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetPaneBorderFormat(ctx context.Context) error {
	return o.target.set(ctx, "pane-border-format", "", true)
}

// ModeStyle observes mode-style; inherited origins may be unavailable.
func (o WindowOptions) ModeStyle(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "mode-style")
}

// SetModeStyle sets the mode-style option in this scope.
func (o WindowOptions) SetModeStyle(ctx context.Context, value string) error {

	return o.target.set(ctx, "mode-style", value, false)
}

// UnsetModeStyle unsets the mode-style option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetModeStyle(ctx context.Context) error {
	return o.target.set(ctx, "mode-style", "", true)
}

// WindowStatusFormat observes window-status-format; inherited origins may be unavailable.
func (o WindowOptions) WindowStatusFormat(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "window-status-format")
}

// SetWindowStatusFormat sets the window-status-format option in this scope.
func (o WindowOptions) SetWindowStatusFormat(ctx context.Context, value string) error {

	return o.target.set(ctx, "window-status-format", value, false)
}

// UnsetWindowStatusFormat unsets the window-status-format option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetWindowStatusFormat(ctx context.Context) error {
	return o.target.set(ctx, "window-status-format", "", true)
}

// WindowStatusCurrentFormat observes window-status-current-format; inherited origins may be unavailable.
func (o WindowOptions) WindowStatusCurrentFormat(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "window-status-current-format")
}

// SetWindowStatusCurrentFormat sets the window-status-current-format option in this scope.
func (o WindowOptions) SetWindowStatusCurrentFormat(ctx context.Context, value string) error {

	return o.target.set(ctx, "window-status-current-format", value, false)
}

// UnsetWindowStatusCurrentFormat unsets the window-status-current-format option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetWindowStatusCurrentFormat(ctx context.Context) error {
	return o.target.set(ctx, "window-status-current-format", "", true)
}

// AllowPassthrough observes allow-passthrough; inherited origins may be unavailable.
func (o WindowOptions) AllowPassthrough(ctx context.Context) (OptionValue[PassthroughPolicy], error) {

	v, err := o.target.read(ctx, "allow-passthrough")
	if err != nil {
		return OptionValue[PassthroughPolicy]{}, err
	}
	r, err := convertOption(v, func(s string) (PassthroughPolicy, error) { return PassthroughPolicy(s), nil })
	if err != nil {
		return OptionValue[PassthroughPolicy]{}, afterError("AllowPassthrough", err)
	}
	return r, nil

}

// SetAllowPassthrough sets the allow-passthrough option in this scope.
func (o WindowOptions) SetAllowPassthrough(ctx context.Context, value PassthroughPolicy) error {
	if !value.valid() {
		return opError("SetAllowPassthrough", invalid("enum value"))
	}

	return o.target.set(ctx, "allow-passthrough", string(value), false)
}

// UnsetAllowPassthrough unsets the allow-passthrough option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetAllowPassthrough(ctx context.Context) error {
	return o.target.set(ctx, "allow-passthrough", "", true)
}
