// Code generated by internal/schema/generate; DO NOT EDIT.

package tmux

import (
	"context"
	"strconv"
)

// ClipboardMode selects a supported tmux option value.
type ClipboardMode string

const (
	ClipboardExternal ClipboardMode = "external"
	ClipboardOff      ClipboardMode = "off"
	ClipboardOn       ClipboardMode = "on"
)

func (v ClipboardMode) valid() bool {
	switch v {
	case ClipboardExternal, ClipboardOff, ClipboardOn:
		return true
	}
	return false
}

// DetachPolicy selects a supported tmux option value.
type DetachPolicy string

const (
	DetachPolicyNext       DetachPolicy = "next"
	DetachPolicyNoDetached DetachPolicy = "no-detached"
	DetachPolicyOff        DetachPolicy = "off"
	DetachPolicyOn         DetachPolicy = "on"
	DetachPolicyPrevious   DetachPolicy = "previous"
)

func (v DetachPolicy) valid() bool {
	switch v {
	case DetachPolicyNext, DetachPolicyNoDetached, DetachPolicyOff, DetachPolicyOn, DetachPolicyPrevious:
		return true
	}
	return false
}

// ModeKeys selects a supported tmux option value.
type ModeKeys string

const (
	ModeKeysEmacs ModeKeys = "emacs"
	ModeKeysVi    ModeKeys = "vi"
)

func (v ModeKeys) valid() bool {
	switch v {
	case ModeKeysEmacs, ModeKeysVi:
		return true
	}
	return false
}

// PaneBorderStatus selects a supported tmux option value.
type PaneBorderStatus string

const (
	PaneBorderStatusBottom PaneBorderStatus = "bottom"
	PaneBorderStatusOff    PaneBorderStatus = "off"
	PaneBorderStatusTop    PaneBorderStatus = "top"
)

func (v PaneBorderStatus) valid() bool {
	switch v {
	case PaneBorderStatusBottom, PaneBorderStatusOff, PaneBorderStatusTop:
		return true
	}
	return false
}

// PassthroughPolicy selects a supported tmux option value.
type PassthroughPolicy string

const (
	PassthroughAll PassthroughPolicy = "all"
	PassthroughOff PassthroughPolicy = "off"
	PassthroughOn  PassthroughPolicy = "on"
)

func (v PassthroughPolicy) valid() bool {
	switch v {
	case PassthroughAll, PassthroughOff, PassthroughOn:
		return true
	}
	return false
}

// RemainOnExitPolicy selects a supported tmux option value.
type RemainOnExitPolicy string

const (
	RemainFailed RemainOnExitPolicy = "failed"
	RemainOff    RemainOnExitPolicy = "off"
	RemainOn     RemainOnExitPolicy = "on"
)

func (v RemainOnExitPolicy) valid() bool {
	switch v {
	case RemainFailed, RemainOff, RemainOn:
		return true
	}
	return false
}

// StatusMode selects a supported tmux option value.
type StatusMode string

const (
	StatusModeFiveLines  StatusMode = "5"
	StatusModeFourLines  StatusMode = "4"
	StatusModeOff        StatusMode = "off"
	StatusModeOn         StatusMode = "on"
	StatusModeThreeLines StatusMode = "3"
	StatusModeTwoLines   StatusMode = "2"
)

func (v StatusMode) valid() bool {
	switch v {
	case StatusModeFiveLines, StatusModeFourLines, StatusModeOff, StatusModeOn, StatusModeThreeLines, StatusModeTwoLines:
		return true
	}
	return false
}

// StatusPosition selects a supported tmux option value.
type StatusPosition string

const (
	StatusPositionBottom StatusPosition = "bottom"
	StatusPositionTop    StatusPosition = "top"
)

func (v StatusPosition) valid() bool {
	switch v {
	case StatusPositionBottom, StatusPositionTop:
		return true
	}
	return false
}

// WindowSizePolicy selects a supported tmux option value.
type WindowSizePolicy string

const (
	WindowSizeLargest  WindowSizePolicy = "largest"
	WindowSizeLatest   WindowSizePolicy = "latest"
	WindowSizeManual   WindowSizePolicy = "manual"
	WindowSizeSmallest WindowSizePolicy = "smallest"
)

func (v WindowSizePolicy) valid() bool {
	switch v {
	case WindowSizeLargest, WindowSizeLatest, WindowSizeManual, WindowSizeSmallest:
		return true
	}
	return false
}

// Get reads a scalar option by its tmux name, preserving local and effective values.
func (o PaneOptions) Get(ctx context.Context, name string) (OptionValue[string], error) {
	return o.target.read(ctx, "PaneOptions.Get", name)
}

// Set sets a scalar option by its tmux name. Tmux validates the value.
func (o PaneOptions) Set(ctx context.Context, name, value string) error {
	return o.target.set(ctx, "PaneOptions.Set", name, value, false)
}

// SetWith sets a scalar option with custom options (such as -a for append, -F for format expansion, or -o for only-if-unset).
func (o PaneOptions) SetWith(ctx context.Context, name string, opts SetOptionOptions) error {
	return o.target.setWith(ctx, "PaneOptions.Set", name, opts)
}

// Unset removes the local value of an option by its tmux name.
func (o PaneOptions) Unset(ctx context.Context, name string) error {
	return o.target.set(ctx, "PaneOptions.Unset", name, "", true)
}

// UnsetWith removes an option with custom options (such as -U for cascading unset from window to panes).
func (o PaneOptions) UnsetWith(ctx context.Context, name string, opts UnsetOptionOptions) error {
	return o.target.unsetWith(ctx, "PaneOptions.Unset", name, opts)
}

// List queries all options set in this scope.
func (o PaneOptions) List(ctx context.Context) ([]OptionEntry, error) {
	return o.target.list(ctx, "PaneOptions.List", ListOptionOptions{})
}

// ListWith queries options set in this scope with custom options (such as -A for inherited or -H for hooks).
func (o PaneOptions) ListWith(ctx context.Context, opts ListOptionOptions) ([]OptionEntry, error) {
	return o.target.list(ctx, "PaneOptions.List", opts)
}

// User reads the value of a user-defined option (prefixed with @) in this scope.
func (o PaneOptions) User(ctx context.Context, name string) (OptionValue[string], error) {
	return userGet(ctx, "PaneOptions.User", o.target, name)
}

// SetUser sets the value of a user-defined option (prefixed with @) in this scope.
func (o PaneOptions) SetUser(ctx context.Context, name, value string) error {
	return userSet(ctx, "PaneOptions.SetUser", o.target, name, value, false)
}

// SetUserWith sets a user-defined option (prefixed with @) with custom mutation options.
func (o PaneOptions) SetUserWith(ctx context.Context, name string, opts SetOptionOptions) error {
	return userSetWith(ctx, "PaneOptions.SetUser", o.target, name, opts)
}

// UnsetUser removes a user-defined option (prefixed with @) from this scope.
func (o PaneOptions) UnsetUser(ctx context.Context, name string) error {
	return userSet(ctx, "PaneOptions.UnsetUser", o.target, name, "", true)
}

// UnsetUserWith unsets a user-defined option (prefixed with @) with custom options.
func (o PaneOptions) UnsetUserWith(ctx context.Context, name string, opts UnsetOptionOptions) error {
	return userUnsetWith(ctx, "PaneOptions.UnsetUser", o.target, name, opts)
}
func (o PaneOptions) Array(ctx context.Context, name string) ([]ArrayEntry, error) {
	return o.target.array(ctx, "PaneOptions.Array", name)
}

// UpdateArray applies a batch of index updates and deletions to the named array option.
func (o PaneOptions) UpdateArray(ctx context.Context, name string, updates []ArrayUpdate) (ArrayUpdateResult, error) {
	return o.target.updateArray(ctx, "PaneOptions.UpdateArray", name, updates)
}

// RemainOnExit observes remain-on-exit; inherited origins may be unavailable.
func (o PaneOptions) RemainOnExit(ctx context.Context) (OptionValue[RemainOnExitPolicy], error) {

	v, err := o.target.read(ctx, "PaneOptions.RemainOnExit", "remain-on-exit")
	if err != nil {
		return OptionValue[RemainOnExitPolicy]{}, err
	}
	r, err := convertOption(v, func(s string) (RemainOnExitPolicy, error) { return RemainOnExitPolicy(s), nil })
	if err != nil {
		return OptionValue[RemainOnExitPolicy]{}, afterError("PaneOptions.RemainOnExit", err)
	}
	return r, nil

}

// SetRemainOnExit sets the remain-on-exit option in this scope.
func (o PaneOptions) SetRemainOnExit(ctx context.Context, value RemainOnExitPolicy) error {
	if !value.valid() {
		return opError("PaneOptions.SetRemainOnExit", invalid("enum value"))
	}

	return o.target.set(ctx, "PaneOptions.SetRemainOnExit", "remain-on-exit", string(value), false)
}

// UnsetRemainOnExit unsets the remain-on-exit option in this scope, restoring inherited defaults.
func (o PaneOptions) UnsetRemainOnExit(ctx context.Context) error {
	return o.target.set(ctx, "PaneOptions.UnsetRemainOnExit", "remain-on-exit", "", true)
}

// SynchronizePanes observes synchronize-panes; inherited origins may be unavailable.
func (o PaneOptions) SynchronizePanes(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "PaneOptions.SynchronizePanes", "synchronize-panes")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("PaneOptions.SynchronizePanes", err)
	}
	return r, nil

}

// SetSynchronizePanes sets the synchronize-panes option in this scope.
func (o PaneOptions) SetSynchronizePanes(ctx context.Context, value bool) error {

	return o.target.set(ctx, "PaneOptions.SetSynchronizePanes", "synchronize-panes", boolOption(value), false)
}

// UnsetSynchronizePanes unsets the synchronize-panes option in this scope, restoring inherited defaults.
func (o PaneOptions) UnsetSynchronizePanes(ctx context.Context) error {
	return o.target.set(ctx, "PaneOptions.UnsetSynchronizePanes", "synchronize-panes", "", true)
}

// AllowPassthrough observes allow-passthrough; inherited origins may be unavailable.
func (o PaneOptions) AllowPassthrough(ctx context.Context) (OptionValue[PassthroughPolicy], error) {

	v, err := o.target.read(ctx, "PaneOptions.AllowPassthrough", "allow-passthrough")
	if err != nil {
		return OptionValue[PassthroughPolicy]{}, err
	}
	r, err := convertOption(v, func(s string) (PassthroughPolicy, error) { return PassthroughPolicy(s), nil })
	if err != nil {
		return OptionValue[PassthroughPolicy]{}, afterError("PaneOptions.AllowPassthrough", err)
	}
	return r, nil

}

// SetAllowPassthrough sets the allow-passthrough option in this scope.
func (o PaneOptions) SetAllowPassthrough(ctx context.Context, value PassthroughPolicy) error {
	if !value.valid() {
		return opError("PaneOptions.SetAllowPassthrough", invalid("enum value"))
	}

	return o.target.set(ctx, "PaneOptions.SetAllowPassthrough", "allow-passthrough", string(value), false)
}

// UnsetAllowPassthrough unsets the allow-passthrough option in this scope, restoring inherited defaults.
func (o PaneOptions) UnsetAllowPassthrough(ctx context.Context) error {
	return o.target.set(ctx, "PaneOptions.UnsetAllowPassthrough", "allow-passthrough", "", true)
}

// AllowRename observes allow-rename; inherited origins may be unavailable.
func (o PaneOptions) AllowRename(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "PaneOptions.AllowRename", "allow-rename")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("PaneOptions.AllowRename", err)
	}
	return r, nil

}

// SetAllowRename sets the allow-rename option in this scope.
func (o PaneOptions) SetAllowRename(ctx context.Context, value bool) error {

	return o.target.set(ctx, "PaneOptions.SetAllowRename", "allow-rename", boolOption(value), false)
}

// UnsetAllowRename unsets the allow-rename option in this scope, restoring inherited defaults.
func (o PaneOptions) UnsetAllowRename(ctx context.Context) error {
	return o.target.set(ctx, "PaneOptions.UnsetAllowRename", "allow-rename", "", true)
}

// ScrollOnClear observes scroll-on-clear; inherited origins may be unavailable.
func (o PaneOptions) ScrollOnClear(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "PaneOptions.ScrollOnClear", "scroll-on-clear")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("PaneOptions.ScrollOnClear", err)
	}
	return r, nil

}

// SetScrollOnClear sets the scroll-on-clear option in this scope.
func (o PaneOptions) SetScrollOnClear(ctx context.Context, value bool) error {

	return o.target.set(ctx, "PaneOptions.SetScrollOnClear", "scroll-on-clear", boolOption(value), false)
}

// UnsetScrollOnClear unsets the scroll-on-clear option in this scope, restoring inherited defaults.
func (o PaneOptions) UnsetScrollOnClear(ctx context.Context) error {
	return o.target.set(ctx, "PaneOptions.UnsetScrollOnClear", "scroll-on-clear", "", true)
}

// WindowStyle observes window-style; inherited origins may be unavailable.
func (o PaneOptions) WindowStyle(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "PaneOptions.WindowStyle", "window-style")
}

// SetWindowStyle sets the window-style option in this scope.
func (o PaneOptions) SetWindowStyle(ctx context.Context, value string) error {

	return o.target.set(ctx, "PaneOptions.SetWindowStyle", "window-style", value, false)
}

// UnsetWindowStyle unsets the window-style option in this scope, restoring inherited defaults.
func (o PaneOptions) UnsetWindowStyle(ctx context.Context) error {
	return o.target.set(ctx, "PaneOptions.UnsetWindowStyle", "window-style", "", true)
}

// WindowActiveStyle observes window-active-style; inherited origins may be unavailable.
func (o PaneOptions) WindowActiveStyle(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "PaneOptions.WindowActiveStyle", "window-active-style")
}

// SetWindowActiveStyle sets the window-active-style option in this scope.
func (o PaneOptions) SetWindowActiveStyle(ctx context.Context, value string) error {

	return o.target.set(ctx, "PaneOptions.SetWindowActiveStyle", "window-active-style", value, false)
}

// UnsetWindowActiveStyle unsets the window-active-style option in this scope, restoring inherited defaults.
func (o PaneOptions) UnsetWindowActiveStyle(ctx context.Context) error {
	return o.target.set(ctx, "PaneOptions.UnsetWindowActiveStyle", "window-active-style", "", true)
}

// Get reads a scalar option by its tmux name, preserving local and effective values.
func (o ServerOptions) Get(ctx context.Context, name string) (OptionValue[string], error) {
	return o.target.read(ctx, "ServerOptions.Get", name)
}

// Set sets a scalar option by its tmux name. Tmux validates the value.
func (o ServerOptions) Set(ctx context.Context, name, value string) error {
	return o.target.set(ctx, "ServerOptions.Set", name, value, false)
}

// SetWith sets a scalar option with custom options (such as -a for append, -F for format expansion, or -o for only-if-unset).
func (o ServerOptions) SetWith(ctx context.Context, name string, opts SetOptionOptions) error {
	return o.target.setWith(ctx, "ServerOptions.Set", name, opts)
}

// Unset removes the local value of an option by its tmux name.
func (o ServerOptions) Unset(ctx context.Context, name string) error {
	return o.target.set(ctx, "ServerOptions.Unset", name, "", true)
}

// UnsetWith removes an option with custom options (such as -U for cascading unset from window to panes).
func (o ServerOptions) UnsetWith(ctx context.Context, name string, opts UnsetOptionOptions) error {
	return o.target.unsetWith(ctx, "ServerOptions.Unset", name, opts)
}

// List queries all options set in this scope.
func (o ServerOptions) List(ctx context.Context) ([]OptionEntry, error) {
	return o.target.list(ctx, "ServerOptions.List", ListOptionOptions{})
}

// ListWith queries options set in this scope with custom options (such as -A for inherited or -H for hooks).
func (o ServerOptions) ListWith(ctx context.Context, opts ListOptionOptions) ([]OptionEntry, error) {
	return o.target.list(ctx, "ServerOptions.List", opts)
}

// User reads the value of a user-defined option (prefixed with @) in this scope.
func (o ServerOptions) User(ctx context.Context, name string) (OptionValue[string], error) {
	return userGet(ctx, "ServerOptions.User", o.target, name)
}

// SetUser sets the value of a user-defined option (prefixed with @) in this scope.
func (o ServerOptions) SetUser(ctx context.Context, name, value string) error {
	return userSet(ctx, "ServerOptions.SetUser", o.target, name, value, false)
}

// SetUserWith sets a user-defined option (prefixed with @) with custom mutation options.
func (o ServerOptions) SetUserWith(ctx context.Context, name string, opts SetOptionOptions) error {
	return userSetWith(ctx, "ServerOptions.SetUser", o.target, name, opts)
}

// UnsetUser removes a user-defined option (prefixed with @) from this scope.
func (o ServerOptions) UnsetUser(ctx context.Context, name string) error {
	return userSet(ctx, "ServerOptions.UnsetUser", o.target, name, "", true)
}

// UnsetUserWith unsets a user-defined option (prefixed with @) with custom options.
func (o ServerOptions) UnsetUserWith(ctx context.Context, name string, opts UnsetOptionOptions) error {
	return userUnsetWith(ctx, "ServerOptions.UnsetUser", o.target, name, opts)
}
func (o ServerOptions) Array(ctx context.Context, name string) ([]ArrayEntry, error) {
	return o.target.array(ctx, "ServerOptions.Array", name)
}

// UpdateArray applies a batch of index updates and deletions to the named array option.
func (o ServerOptions) UpdateArray(ctx context.Context, name string, updates []ArrayUpdate) (ArrayUpdateResult, error) {
	return o.target.updateArray(ctx, "ServerOptions.UpdateArray", name, updates)
}

// EscapeTime observes escape-time; inherited origins may be unavailable.
func (o ServerOptions) EscapeTime(ctx context.Context) (OptionValue[int], error) {

	v, err := o.target.read(ctx, "ServerOptions.EscapeTime", "escape-time")
	if err != nil {
		return OptionValue[int]{}, err
	}
	r, err := convertOption(v, parseOptionInt)
	if err != nil {
		return OptionValue[int]{}, afterError("ServerOptions.EscapeTime", err)
	}
	return r, nil

}

// SetEscapeTime sets the escape-time option in this scope.
func (o ServerOptions) SetEscapeTime(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("ServerOptions.SetEscapeTime", invalid("range"))
	}

	return o.target.set(ctx, "ServerOptions.SetEscapeTime", "escape-time", strconv.Itoa(value), false)
}

// UnsetEscapeTime unsets the escape-time option in this scope, restoring inherited defaults.
func (o ServerOptions) UnsetEscapeTime(ctx context.Context) error {
	return o.target.set(ctx, "ServerOptions.UnsetEscapeTime", "escape-time", "", true)
}

// BufferLimit observes buffer-limit; inherited origins may be unavailable.
func (o ServerOptions) BufferLimit(ctx context.Context) (OptionValue[int], error) {

	v, err := o.target.read(ctx, "ServerOptions.BufferLimit", "buffer-limit")
	if err != nil {
		return OptionValue[int]{}, err
	}
	r, err := convertOption(v, parseOptionInt)
	if err != nil {
		return OptionValue[int]{}, afterError("ServerOptions.BufferLimit", err)
	}
	return r, nil

}

// SetBufferLimit sets the buffer-limit option in this scope.
func (o ServerOptions) SetBufferLimit(ctx context.Context, value int) error {
	if value < 1 || value > 2147483647 {
		return opError("ServerOptions.SetBufferLimit", invalid("range"))
	}

	return o.target.set(ctx, "ServerOptions.SetBufferLimit", "buffer-limit", strconv.Itoa(value), false)
}

// UnsetBufferLimit unsets the buffer-limit option in this scope, restoring inherited defaults.
func (o ServerOptions) UnsetBufferLimit(ctx context.Context) error {
	return o.target.set(ctx, "ServerOptions.UnsetBufferLimit", "buffer-limit", "", true)
}

// ExitEmpty observes exit-empty; inherited origins may be unavailable.
func (o ServerOptions) ExitEmpty(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "ServerOptions.ExitEmpty", "exit-empty")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("ServerOptions.ExitEmpty", err)
	}
	return r, nil

}

// SetExitEmpty sets the exit-empty option in this scope.
func (o ServerOptions) SetExitEmpty(ctx context.Context, value bool) error {

	return o.target.set(ctx, "ServerOptions.SetExitEmpty", "exit-empty", boolOption(value), false)
}

// UnsetExitEmpty unsets the exit-empty option in this scope, restoring inherited defaults.
func (o ServerOptions) UnsetExitEmpty(ctx context.Context) error {
	return o.target.set(ctx, "ServerOptions.UnsetExitEmpty", "exit-empty", "", true)
}

// ExitUnattached observes exit-unattached; inherited origins may be unavailable.
func (o ServerOptions) ExitUnattached(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "ServerOptions.ExitUnattached", "exit-unattached")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("ServerOptions.ExitUnattached", err)
	}
	return r, nil

}

// SetExitUnattached sets the exit-unattached option in this scope.
func (o ServerOptions) SetExitUnattached(ctx context.Context, value bool) error {

	return o.target.set(ctx, "ServerOptions.SetExitUnattached", "exit-unattached", boolOption(value), false)
}

// UnsetExitUnattached unsets the exit-unattached option in this scope, restoring inherited defaults.
func (o ServerOptions) UnsetExitUnattached(ctx context.Context) error {
	return o.target.set(ctx, "ServerOptions.UnsetExitUnattached", "exit-unattached", "", true)
}

// DefaultTerminal observes default-terminal; inherited origins may be unavailable.
func (o ServerOptions) DefaultTerminal(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "ServerOptions.DefaultTerminal", "default-terminal")
}

// SetDefaultTerminal sets the default-terminal option in this scope.
func (o ServerOptions) SetDefaultTerminal(ctx context.Context, value string) error {

	return o.target.set(ctx, "ServerOptions.SetDefaultTerminal", "default-terminal", value, false)
}

// UnsetDefaultTerminal unsets the default-terminal option in this scope, restoring inherited defaults.
func (o ServerOptions) UnsetDefaultTerminal(ctx context.Context) error {
	return o.target.set(ctx, "ServerOptions.UnsetDefaultTerminal", "default-terminal", "", true)
}

// Clipboard observes set-clipboard; inherited origins may be unavailable.
func (o ServerOptions) Clipboard(ctx context.Context) (OptionValue[ClipboardMode], error) {

	v, err := o.target.read(ctx, "ServerOptions.Clipboard", "set-clipboard")
	if err != nil {
		return OptionValue[ClipboardMode]{}, err
	}
	r, err := convertOption(v, func(s string) (ClipboardMode, error) { return ClipboardMode(s), nil })
	if err != nil {
		return OptionValue[ClipboardMode]{}, afterError("ServerOptions.Clipboard", err)
	}
	return r, nil

}

// SetClipboard sets the set-clipboard option in this scope.
func (o ServerOptions) SetClipboard(ctx context.Context, value ClipboardMode) error {
	if !value.valid() {
		return opError("ServerOptions.SetClipboard", invalid("enum value"))
	}

	return o.target.set(ctx, "ServerOptions.SetClipboard", "set-clipboard", string(value), false)
}

// UnsetClipboard unsets the set-clipboard option in this scope, restoring inherited defaults.
func (o ServerOptions) UnsetClipboard(ctx context.Context) error {
	return o.target.set(ctx, "ServerOptions.UnsetClipboard", "set-clipboard", "", true)
}

// HistoryFile observes history-file; inherited origins may be unavailable.
func (o ServerOptions) HistoryFile(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "ServerOptions.HistoryFile", "history-file")
}

// SetHistoryFile sets the history-file option in this scope.
func (o ServerOptions) SetHistoryFile(ctx context.Context, value string) error {

	return o.target.set(ctx, "ServerOptions.SetHistoryFile", "history-file", value, false)
}

// UnsetHistoryFile unsets the history-file option in this scope, restoring inherited defaults.
func (o ServerOptions) UnsetHistoryFile(ctx context.Context) error {
	return o.target.set(ctx, "ServerOptions.UnsetHistoryFile", "history-file", "", true)
}

// Get reads a scalar option by its tmux name, preserving local and effective values.
func (o SessionOptions) Get(ctx context.Context, name string) (OptionValue[string], error) {
	return o.target.read(ctx, "SessionOptions.Get", name)
}

// Set sets a scalar option by its tmux name. Tmux validates the value.
func (o SessionOptions) Set(ctx context.Context, name, value string) error {
	return o.target.set(ctx, "SessionOptions.Set", name, value, false)
}

// SetWith sets a scalar option with custom options (such as -a for append, -F for format expansion, or -o for only-if-unset).
func (o SessionOptions) SetWith(ctx context.Context, name string, opts SetOptionOptions) error {
	return o.target.setWith(ctx, "SessionOptions.Set", name, opts)
}

// Unset removes the local value of an option by its tmux name.
func (o SessionOptions) Unset(ctx context.Context, name string) error {
	return o.target.set(ctx, "SessionOptions.Unset", name, "", true)
}

// UnsetWith removes an option with custom options (such as -U for cascading unset from window to panes).
func (o SessionOptions) UnsetWith(ctx context.Context, name string, opts UnsetOptionOptions) error {
	return o.target.unsetWith(ctx, "SessionOptions.Unset", name, opts)
}

// List queries all options set in this scope.
func (o SessionOptions) List(ctx context.Context) ([]OptionEntry, error) {
	return o.target.list(ctx, "SessionOptions.List", ListOptionOptions{})
}

// ListWith queries options set in this scope with custom options (such as -A for inherited or -H for hooks).
func (o SessionOptions) ListWith(ctx context.Context, opts ListOptionOptions) ([]OptionEntry, error) {
	return o.target.list(ctx, "SessionOptions.List", opts)
}

// User reads the value of a user-defined option (prefixed with @) in this scope.
func (o SessionOptions) User(ctx context.Context, name string) (OptionValue[string], error) {
	return userGet(ctx, "SessionOptions.User", o.target, name)
}

// SetUser sets the value of a user-defined option (prefixed with @) in this scope.
func (o SessionOptions) SetUser(ctx context.Context, name, value string) error {
	return userSet(ctx, "SessionOptions.SetUser", o.target, name, value, false)
}

// SetUserWith sets a user-defined option (prefixed with @) with custom mutation options.
func (o SessionOptions) SetUserWith(ctx context.Context, name string, opts SetOptionOptions) error {
	return userSetWith(ctx, "SessionOptions.SetUser", o.target, name, opts)
}

// UnsetUser removes a user-defined option (prefixed with @) from this scope.
func (o SessionOptions) UnsetUser(ctx context.Context, name string) error {
	return userSet(ctx, "SessionOptions.UnsetUser", o.target, name, "", true)
}

// UnsetUserWith unsets a user-defined option (prefixed with @) with custom options.
func (o SessionOptions) UnsetUserWith(ctx context.Context, name string, opts UnsetOptionOptions) error {
	return userUnsetWith(ctx, "SessionOptions.UnsetUser", o.target, name, opts)
}
func (o SessionOptions) Array(ctx context.Context, name string) ([]ArrayEntry, error) {
	return o.target.array(ctx, "SessionOptions.Array", name)
}

// UpdateArray applies a batch of index updates and deletions to the named array option.
func (o SessionOptions) UpdateArray(ctx context.Context, name string, updates []ArrayUpdate) (ArrayUpdateResult, error) {
	return o.target.updateArray(ctx, "SessionOptions.UpdateArray", name, updates)
}

// HistoryLimit observes history-limit; inherited origins may be unavailable.
func (o SessionOptions) HistoryLimit(ctx context.Context) (OptionValue[int], error) {

	v, err := o.target.read(ctx, "SessionOptions.HistoryLimit", "history-limit")
	if err != nil {
		return OptionValue[int]{}, err
	}
	r, err := convertOption(v, parseOptionInt)
	if err != nil {
		return OptionValue[int]{}, afterError("SessionOptions.HistoryLimit", err)
	}
	return r, nil

}

// SetHistoryLimit sets the history-limit option in this scope.
func (o SessionOptions) SetHistoryLimit(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SessionOptions.SetHistoryLimit", invalid("range"))
	}

	return o.target.set(ctx, "SessionOptions.SetHistoryLimit", "history-limit", strconv.Itoa(value), false)
}

// UnsetHistoryLimit unsets the history-limit option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetHistoryLimit(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetHistoryLimit", "history-limit", "", true)
}

// BaseIndex observes base-index; inherited origins may be unavailable.
func (o SessionOptions) BaseIndex(ctx context.Context) (OptionValue[int], error) {

	v, err := o.target.read(ctx, "SessionOptions.BaseIndex", "base-index")
	if err != nil {
		return OptionValue[int]{}, err
	}
	r, err := convertOption(v, parseOptionInt)
	if err != nil {
		return OptionValue[int]{}, afterError("SessionOptions.BaseIndex", err)
	}
	return r, nil

}

// SetBaseIndex sets the base-index option in this scope.
func (o SessionOptions) SetBaseIndex(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SessionOptions.SetBaseIndex", invalid("range"))
	}

	return o.target.set(ctx, "SessionOptions.SetBaseIndex", "base-index", strconv.Itoa(value), false)
}

// UnsetBaseIndex unsets the base-index option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetBaseIndex(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetBaseIndex", "base-index", "", true)
}

// DisplayTime observes display-time; inherited origins may be unavailable.
func (o SessionOptions) DisplayTime(ctx context.Context) (OptionValue[int], error) {

	v, err := o.target.read(ctx, "SessionOptions.DisplayTime", "display-time")
	if err != nil {
		return OptionValue[int]{}, err
	}
	r, err := convertOption(v, parseOptionInt)
	if err != nil {
		return OptionValue[int]{}, afterError("SessionOptions.DisplayTime", err)
	}
	return r, nil

}

// SetDisplayTime sets the display-time option in this scope.
func (o SessionOptions) SetDisplayTime(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SessionOptions.SetDisplayTime", invalid("range"))
	}

	return o.target.set(ctx, "SessionOptions.SetDisplayTime", "display-time", strconv.Itoa(value), false)
}

// UnsetDisplayTime unsets the display-time option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetDisplayTime(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetDisplayTime", "display-time", "", true)
}

// RepeatTime observes repeat-time; inherited origins may be unavailable.
func (o SessionOptions) RepeatTime(ctx context.Context) (OptionValue[int], error) {

	v, err := o.target.read(ctx, "SessionOptions.RepeatTime", "repeat-time")
	if err != nil {
		return OptionValue[int]{}, err
	}
	r, err := convertOption(v, parseOptionInt)
	if err != nil {
		return OptionValue[int]{}, afterError("SessionOptions.RepeatTime", err)
	}
	return r, nil

}

// SetRepeatTime sets the repeat-time option in this scope.
func (o SessionOptions) SetRepeatTime(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("SessionOptions.SetRepeatTime", invalid("range"))
	}

	return o.target.set(ctx, "SessionOptions.SetRepeatTime", "repeat-time", strconv.Itoa(value), false)
}

// UnsetRepeatTime unsets the repeat-time option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetRepeatTime(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetRepeatTime", "repeat-time", "", true)
}

// Mouse observes mouse; inherited origins may be unavailable.
func (o SessionOptions) Mouse(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "SessionOptions.Mouse", "mouse")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("SessionOptions.Mouse", err)
	}
	return r, nil

}

// SetMouse sets the mouse option in this scope.
func (o SessionOptions) SetMouse(ctx context.Context, value bool) error {

	return o.target.set(ctx, "SessionOptions.SetMouse", "mouse", boolOption(value), false)
}

// UnsetMouse unsets the mouse option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetMouse(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetMouse", "mouse", "", true)
}

// Titles observes set-titles; inherited origins may be unavailable.
func (o SessionOptions) Titles(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "SessionOptions.Titles", "set-titles")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("SessionOptions.Titles", err)
	}
	return r, nil

}

// SetTitles sets the set-titles option in this scope.
func (o SessionOptions) SetTitles(ctx context.Context, value bool) error {

	return o.target.set(ctx, "SessionOptions.SetTitles", "set-titles", boolOption(value), false)
}

// UnsetTitles unsets the set-titles option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetTitles(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetTitles", "set-titles", "", true)
}

// DefaultShell observes default-shell; inherited origins may be unavailable.
func (o SessionOptions) DefaultShell(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "SessionOptions.DefaultShell", "default-shell")
}

// SetDefaultShell sets the default-shell option in this scope.
func (o SessionOptions) SetDefaultShell(ctx context.Context, value string) error {

	return o.target.set(ctx, "SessionOptions.SetDefaultShell", "default-shell", value, false)
}

// UnsetDefaultShell unsets the default-shell option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetDefaultShell(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetDefaultShell", "default-shell", "", true)
}

// DefaultCommand observes default-command; inherited origins may be unavailable.
func (o SessionOptions) DefaultCommand(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "SessionOptions.DefaultCommand", "default-command")
}

// SetDefaultCommand sets the default-command option in this scope.
func (o SessionOptions) SetDefaultCommand(ctx context.Context, value string) error {

	return o.target.set(ctx, "SessionOptions.SetDefaultCommand", "default-command", value, false)
}

// UnsetDefaultCommand unsets the default-command option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetDefaultCommand(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetDefaultCommand", "default-command", "", true)
}

// DefaultSize observes default-size; inherited origins may be unavailable.
func (o SessionOptions) DefaultSize(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "SessionOptions.DefaultSize", "default-size")
}

// SetDefaultSize sets the default-size option in this scope.
func (o SessionOptions) SetDefaultSize(ctx context.Context, value string) error {

	return o.target.set(ctx, "SessionOptions.SetDefaultSize", "default-size", value, false)
}

// UnsetDefaultSize unsets the default-size option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetDefaultSize(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetDefaultSize", "default-size", "", true)
}

// StatusLeft observes status-left; inherited origins may be unavailable.
func (o SessionOptions) StatusLeft(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "SessionOptions.StatusLeft", "status-left")
}

// SetStatusLeft sets the status-left option in this scope.
func (o SessionOptions) SetStatusLeft(ctx context.Context, value string) error {

	return o.target.set(ctx, "SessionOptions.SetStatusLeft", "status-left", value, false)
}

// UnsetStatusLeft unsets the status-left option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetStatusLeft(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetStatusLeft", "status-left", "", true)
}

// StatusRight observes status-right; inherited origins may be unavailable.
func (o SessionOptions) StatusRight(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "SessionOptions.StatusRight", "status-right")
}

// SetStatusRight sets the status-right option in this scope.
func (o SessionOptions) SetStatusRight(ctx context.Context, value string) error {

	return o.target.set(ctx, "SessionOptions.SetStatusRight", "status-right", value, false)
}

// UnsetStatusRight unsets the status-right option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetStatusRight(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetStatusRight", "status-right", "", true)
}

// StatusStyle observes status-style; inherited origins may be unavailable.
func (o SessionOptions) StatusStyle(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "SessionOptions.StatusStyle", "status-style")
}

// SetStatusStyle sets the status-style option in this scope.
func (o SessionOptions) SetStatusStyle(ctx context.Context, value string) error {

	return o.target.set(ctx, "SessionOptions.SetStatusStyle", "status-style", value, false)
}

// UnsetStatusStyle unsets the status-style option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetStatusStyle(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetStatusStyle", "status-style", "", true)
}

// StatusPosition observes status-position; inherited origins may be unavailable.
func (o SessionOptions) StatusPosition(ctx context.Context) (OptionValue[StatusPosition], error) {

	v, err := o.target.read(ctx, "SessionOptions.StatusPosition", "status-position")
	if err != nil {
		return OptionValue[StatusPosition]{}, err
	}
	r, err := convertOption(v, func(s string) (StatusPosition, error) { return StatusPosition(s), nil })
	if err != nil {
		return OptionValue[StatusPosition]{}, afterError("SessionOptions.StatusPosition", err)
	}
	return r, nil

}

// SetStatusPosition sets the status-position option in this scope.
func (o SessionOptions) SetStatusPosition(ctx context.Context, value StatusPosition) error {
	if !value.valid() {
		return opError("SessionOptions.SetStatusPosition", invalid("enum value"))
	}

	return o.target.set(ctx, "SessionOptions.SetStatusPosition", "status-position", string(value), false)
}

// UnsetStatusPosition unsets the status-position option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetStatusPosition(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetStatusPosition", "status-position", "", true)
}

// Status observes status; inherited origins may be unavailable.
func (o SessionOptions) Status(ctx context.Context) (OptionValue[StatusMode], error) {

	v, err := o.target.read(ctx, "SessionOptions.Status", "status")
	if err != nil {
		return OptionValue[StatusMode]{}, err
	}
	r, err := convertOption(v, func(s string) (StatusMode, error) { return StatusMode(s), nil })
	if err != nil {
		return OptionValue[StatusMode]{}, afterError("SessionOptions.Status", err)
	}
	return r, nil

}

// SetStatus sets the status option in this scope.
func (o SessionOptions) SetStatus(ctx context.Context, value StatusMode) error {
	if !value.valid() {
		return opError("SessionOptions.SetStatus", invalid("enum value"))
	}

	return o.target.set(ctx, "SessionOptions.SetStatus", "status", string(value), false)
}

// UnsetStatus unsets the status option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetStatus(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetStatus", "status", "", true)
}

// Prefix observes prefix; inherited origins may be unavailable.
func (o SessionOptions) Prefix(ctx context.Context) (OptionValue[Key], error) {

	v, err := o.target.read(ctx, "SessionOptions.Prefix", "prefix")
	if err != nil {
		return OptionValue[Key]{}, err
	}
	r, err := convertOption(v, func(s string) (Key, error) { return Key(s), nil })
	if err != nil {
		return OptionValue[Key]{}, afterError("SessionOptions.Prefix", err)
	}
	return r, nil

}

// SetPrefix sets the prefix option in this scope.
func (o SessionOptions) SetPrefix(ctx context.Context, value Key) error {
	if !value.Valid() {
		return opError("SessionOptions.SetPrefix", invalid("key value"))
	}
	return o.target.set(ctx, "SessionOptions.SetPrefix", "prefix", string(value), false)
}

// UnsetPrefix unsets the prefix option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetPrefix(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetPrefix", "prefix", "", true)
}

// DetachOnDestroy observes detach-on-destroy; inherited origins may be unavailable.
func (o SessionOptions) DetachOnDestroy(ctx context.Context) (OptionValue[DetachPolicy], error) {

	v, err := o.target.read(ctx, "SessionOptions.DetachOnDestroy", "detach-on-destroy")
	if err != nil {
		return OptionValue[DetachPolicy]{}, err
	}
	r, err := convertOption(v, func(s string) (DetachPolicy, error) { return DetachPolicy(s), nil })
	if err != nil {
		return OptionValue[DetachPolicy]{}, afterError("SessionOptions.DetachOnDestroy", err)
	}
	return r, nil

}

// SetDetachOnDestroy sets the detach-on-destroy option in this scope.
func (o SessionOptions) SetDetachOnDestroy(ctx context.Context, value DetachPolicy) error {
	if !value.valid() {
		return opError("SessionOptions.SetDetachOnDestroy", invalid("enum value"))
	}

	return o.target.set(ctx, "SessionOptions.SetDetachOnDestroy", "detach-on-destroy", string(value), false)
}

// UnsetDetachOnDestroy unsets the detach-on-destroy option in this scope, restoring inherited defaults.
func (o SessionOptions) UnsetDetachOnDestroy(ctx context.Context) error {
	return o.target.set(ctx, "SessionOptions.UnsetDetachOnDestroy", "detach-on-destroy", "", true)
}

// Get reads a scalar option by its tmux name, preserving local and effective values.
func (o WindowOptions) Get(ctx context.Context, name string) (OptionValue[string], error) {
	return o.target.read(ctx, "WindowOptions.Get", name)
}

// Set sets a scalar option by its tmux name. Tmux validates the value.
func (o WindowOptions) Set(ctx context.Context, name, value string) error {
	return o.target.set(ctx, "WindowOptions.Set", name, value, false)
}

// SetWith sets a scalar option with custom options (such as -a for append, -F for format expansion, or -o for only-if-unset).
func (o WindowOptions) SetWith(ctx context.Context, name string, opts SetOptionOptions) error {
	return o.target.setWith(ctx, "WindowOptions.Set", name, opts)
}

// Unset removes the local value of an option by its tmux name.
func (o WindowOptions) Unset(ctx context.Context, name string) error {
	return o.target.set(ctx, "WindowOptions.Unset", name, "", true)
}

// UnsetWith removes an option with custom options (such as -U for cascading unset from window to panes).
func (o WindowOptions) UnsetWith(ctx context.Context, name string, opts UnsetOptionOptions) error {
	return o.target.unsetWith(ctx, "WindowOptions.Unset", name, opts)
}

// List queries all options set in this scope.
func (o WindowOptions) List(ctx context.Context) ([]OptionEntry, error) {
	return o.target.list(ctx, "WindowOptions.List", ListOptionOptions{})
}

// ListWith queries options set in this scope with custom options (such as -A for inherited or -H for hooks).
func (o WindowOptions) ListWith(ctx context.Context, opts ListOptionOptions) ([]OptionEntry, error) {
	return o.target.list(ctx, "WindowOptions.List", opts)
}

// User reads the value of a user-defined option (prefixed with @) in this scope.
func (o WindowOptions) User(ctx context.Context, name string) (OptionValue[string], error) {
	return userGet(ctx, "WindowOptions.User", o.target, name)
}

// SetUser sets the value of a user-defined option (prefixed with @) in this scope.
func (o WindowOptions) SetUser(ctx context.Context, name, value string) error {
	return userSet(ctx, "WindowOptions.SetUser", o.target, name, value, false)
}

// SetUserWith sets a user-defined option (prefixed with @) with custom mutation options.
func (o WindowOptions) SetUserWith(ctx context.Context, name string, opts SetOptionOptions) error {
	return userSetWith(ctx, "WindowOptions.SetUser", o.target, name, opts)
}

// UnsetUser removes a user-defined option (prefixed with @) from this scope.
func (o WindowOptions) UnsetUser(ctx context.Context, name string) error {
	return userSet(ctx, "WindowOptions.UnsetUser", o.target, name, "", true)
}

// UnsetUserWith unsets a user-defined option (prefixed with @) with custom options.
func (o WindowOptions) UnsetUserWith(ctx context.Context, name string, opts UnsetOptionOptions) error {
	return userUnsetWith(ctx, "WindowOptions.UnsetUser", o.target, name, opts)
}
func (o WindowOptions) Array(ctx context.Context, name string) ([]ArrayEntry, error) {
	return o.target.array(ctx, "WindowOptions.Array", name)
}

// UpdateArray applies a batch of index updates and deletions to the named array option.
func (o WindowOptions) UpdateArray(ctx context.Context, name string, updates []ArrayUpdate) (ArrayUpdateResult, error) {
	return o.target.updateArray(ctx, "WindowOptions.UpdateArray", name, updates)
}

// AutomaticRename observes automatic-rename; inherited origins may be unavailable.
func (o WindowOptions) AutomaticRename(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "WindowOptions.AutomaticRename", "automatic-rename")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("WindowOptions.AutomaticRename", err)
	}
	return r, nil

}

// SetAutomaticRename sets the automatic-rename option in this scope.
func (o WindowOptions) SetAutomaticRename(ctx context.Context, value bool) error {

	return o.target.set(ctx, "WindowOptions.SetAutomaticRename", "automatic-rename", boolOption(value), false)
}

// UnsetAutomaticRename unsets the automatic-rename option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetAutomaticRename(ctx context.Context) error {
	return o.target.set(ctx, "WindowOptions.UnsetAutomaticRename", "automatic-rename", "", true)
}

// AllowRename observes allow-rename; inherited origins may be unavailable.
func (o WindowOptions) AllowRename(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "WindowOptions.AllowRename", "allow-rename")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("WindowOptions.AllowRename", err)
	}
	return r, nil

}

// SetAllowRename sets the allow-rename option in this scope.
func (o WindowOptions) SetAllowRename(ctx context.Context, value bool) error {

	return o.target.set(ctx, "WindowOptions.SetAllowRename", "allow-rename", boolOption(value), false)
}

// UnsetAllowRename unsets the allow-rename option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetAllowRename(ctx context.Context) error {
	return o.target.set(ctx, "WindowOptions.UnsetAllowRename", "allow-rename", "", true)
}

// AggressiveResize observes aggressive-resize; inherited origins may be unavailable.
func (o WindowOptions) AggressiveResize(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "WindowOptions.AggressiveResize", "aggressive-resize")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("WindowOptions.AggressiveResize", err)
	}
	return r, nil

}

// SetAggressiveResize sets the aggressive-resize option in this scope.
func (o WindowOptions) SetAggressiveResize(ctx context.Context, value bool) error {

	return o.target.set(ctx, "WindowOptions.SetAggressiveResize", "aggressive-resize", boolOption(value), false)
}

// UnsetAggressiveResize unsets the aggressive-resize option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetAggressiveResize(ctx context.Context) error {
	return o.target.set(ctx, "WindowOptions.UnsetAggressiveResize", "aggressive-resize", "", true)
}

// PaneBaseIndex observes pane-base-index; inherited origins may be unavailable.
func (o WindowOptions) PaneBaseIndex(ctx context.Context) (OptionValue[int], error) {

	v, err := o.target.read(ctx, "WindowOptions.PaneBaseIndex", "pane-base-index")
	if err != nil {
		return OptionValue[int]{}, err
	}
	r, err := convertOption(v, parseOptionInt)
	if err != nil {
		return OptionValue[int]{}, afterError("WindowOptions.PaneBaseIndex", err)
	}
	return r, nil

}

// SetPaneBaseIndex sets the pane-base-index option in this scope.
func (o WindowOptions) SetPaneBaseIndex(ctx context.Context, value int) error {
	if value < 0 || value > 2147483647 {
		return opError("WindowOptions.SetPaneBaseIndex", invalid("range"))
	}

	return o.target.set(ctx, "WindowOptions.SetPaneBaseIndex", "pane-base-index", strconv.Itoa(value), false)
}

// UnsetPaneBaseIndex unsets the pane-base-index option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetPaneBaseIndex(ctx context.Context) error {
	return o.target.set(ctx, "WindowOptions.UnsetPaneBaseIndex", "pane-base-index", "", true)
}

// ModeKeys observes mode-keys; inherited origins may be unavailable.
func (o WindowOptions) ModeKeys(ctx context.Context) (OptionValue[ModeKeys], error) {

	v, err := o.target.read(ctx, "WindowOptions.ModeKeys", "mode-keys")
	if err != nil {
		return OptionValue[ModeKeys]{}, err
	}
	r, err := convertOption(v, func(s string) (ModeKeys, error) { return ModeKeys(s), nil })
	if err != nil {
		return OptionValue[ModeKeys]{}, afterError("WindowOptions.ModeKeys", err)
	}
	return r, nil

}

// SetModeKeys sets the mode-keys option in this scope.
func (o WindowOptions) SetModeKeys(ctx context.Context, value ModeKeys) error {
	if !value.valid() {
		return opError("WindowOptions.SetModeKeys", invalid("enum value"))
	}

	return o.target.set(ctx, "WindowOptions.SetModeKeys", "mode-keys", string(value), false)
}

// UnsetModeKeys unsets the mode-keys option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetModeKeys(ctx context.Context) error {
	return o.target.set(ctx, "WindowOptions.UnsetModeKeys", "mode-keys", "", true)
}

// WindowSize observes window-size; inherited origins may be unavailable.
func (o WindowOptions) WindowSize(ctx context.Context) (OptionValue[WindowSizePolicy], error) {

	v, err := o.target.read(ctx, "WindowOptions.WindowSize", "window-size")
	if err != nil {
		return OptionValue[WindowSizePolicy]{}, err
	}
	r, err := convertOption(v, func(s string) (WindowSizePolicy, error) { return WindowSizePolicy(s), nil })
	if err != nil {
		return OptionValue[WindowSizePolicy]{}, afterError("WindowOptions.WindowSize", err)
	}
	return r, nil

}

// SetWindowSize sets the window-size option in this scope.
func (o WindowOptions) SetWindowSize(ctx context.Context, value WindowSizePolicy) error {
	if !value.valid() {
		return opError("WindowOptions.SetWindowSize", invalid("enum value"))
	}

	return o.target.set(ctx, "WindowOptions.SetWindowSize", "window-size", string(value), false)
}

// UnsetWindowSize unsets the window-size option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetWindowSize(ctx context.Context) error {
	return o.target.set(ctx, "WindowOptions.UnsetWindowSize", "window-size", "", true)
}

// RemainOnExit observes remain-on-exit; inherited origins may be unavailable.
func (o WindowOptions) RemainOnExit(ctx context.Context) (OptionValue[RemainOnExitPolicy], error) {

	v, err := o.target.read(ctx, "WindowOptions.RemainOnExit", "remain-on-exit")
	if err != nil {
		return OptionValue[RemainOnExitPolicy]{}, err
	}
	r, err := convertOption(v, func(s string) (RemainOnExitPolicy, error) { return RemainOnExitPolicy(s), nil })
	if err != nil {
		return OptionValue[RemainOnExitPolicy]{}, afterError("WindowOptions.RemainOnExit", err)
	}
	return r, nil

}

// SetRemainOnExit sets the remain-on-exit option in this scope.
func (o WindowOptions) SetRemainOnExit(ctx context.Context, value RemainOnExitPolicy) error {
	if !value.valid() {
		return opError("WindowOptions.SetRemainOnExit", invalid("enum value"))
	}

	return o.target.set(ctx, "WindowOptions.SetRemainOnExit", "remain-on-exit", string(value), false)
}

// UnsetRemainOnExit unsets the remain-on-exit option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetRemainOnExit(ctx context.Context) error {
	return o.target.set(ctx, "WindowOptions.UnsetRemainOnExit", "remain-on-exit", "", true)
}

// SynchronizePanes observes synchronize-panes; inherited origins may be unavailable.
func (o WindowOptions) SynchronizePanes(ctx context.Context) (OptionValue[bool], error) {

	v, err := o.target.read(ctx, "WindowOptions.SynchronizePanes", "synchronize-panes")
	if err != nil {
		return OptionValue[bool]{}, err
	}
	r, err := convertOption(v, parseOptionBool)
	if err != nil {
		return OptionValue[bool]{}, afterError("WindowOptions.SynchronizePanes", err)
	}
	return r, nil

}

// SetSynchronizePanes sets the synchronize-panes option in this scope.
func (o WindowOptions) SetSynchronizePanes(ctx context.Context, value bool) error {

	return o.target.set(ctx, "WindowOptions.SetSynchronizePanes", "synchronize-panes", boolOption(value), false)
}

// UnsetSynchronizePanes unsets the synchronize-panes option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetSynchronizePanes(ctx context.Context) error {
	return o.target.set(ctx, "WindowOptions.UnsetSynchronizePanes", "synchronize-panes", "", true)
}

// PaneBorderStatus observes pane-border-status; inherited origins may be unavailable.
func (o WindowOptions) PaneBorderStatus(ctx context.Context) (OptionValue[PaneBorderStatus], error) {

	v, err := o.target.read(ctx, "WindowOptions.PaneBorderStatus", "pane-border-status")
	if err != nil {
		return OptionValue[PaneBorderStatus]{}, err
	}
	r, err := convertOption(v, func(s string) (PaneBorderStatus, error) { return PaneBorderStatus(s), nil })
	if err != nil {
		return OptionValue[PaneBorderStatus]{}, afterError("WindowOptions.PaneBorderStatus", err)
	}
	return r, nil

}

// SetPaneBorderStatus sets the pane-border-status option in this scope.
func (o WindowOptions) SetPaneBorderStatus(ctx context.Context, value PaneBorderStatus) error {
	if !value.valid() {
		return opError("WindowOptions.SetPaneBorderStatus", invalid("enum value"))
	}

	return o.target.set(ctx, "WindowOptions.SetPaneBorderStatus", "pane-border-status", string(value), false)
}

// UnsetPaneBorderStatus unsets the pane-border-status option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetPaneBorderStatus(ctx context.Context) error {
	return o.target.set(ctx, "WindowOptions.UnsetPaneBorderStatus", "pane-border-status", "", true)
}

// PaneBorderFormat observes pane-border-format; inherited origins may be unavailable.
func (o WindowOptions) PaneBorderFormat(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "WindowOptions.PaneBorderFormat", "pane-border-format")
}

// SetPaneBorderFormat sets the pane-border-format option in this scope.
func (o WindowOptions) SetPaneBorderFormat(ctx context.Context, value string) error {

	return o.target.set(ctx, "WindowOptions.SetPaneBorderFormat", "pane-border-format", value, false)
}

// UnsetPaneBorderFormat unsets the pane-border-format option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetPaneBorderFormat(ctx context.Context) error {
	return o.target.set(ctx, "WindowOptions.UnsetPaneBorderFormat", "pane-border-format", "", true)
}

// ModeStyle observes mode-style; inherited origins may be unavailable.
func (o WindowOptions) ModeStyle(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "WindowOptions.ModeStyle", "mode-style")
}

// SetModeStyle sets the mode-style option in this scope.
func (o WindowOptions) SetModeStyle(ctx context.Context, value string) error {

	return o.target.set(ctx, "WindowOptions.SetModeStyle", "mode-style", value, false)
}

// UnsetModeStyle unsets the mode-style option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetModeStyle(ctx context.Context) error {
	return o.target.set(ctx, "WindowOptions.UnsetModeStyle", "mode-style", "", true)
}

// WindowStatusFormat observes window-status-format; inherited origins may be unavailable.
func (o WindowOptions) WindowStatusFormat(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "WindowOptions.WindowStatusFormat", "window-status-format")
}

// SetWindowStatusFormat sets the window-status-format option in this scope.
func (o WindowOptions) SetWindowStatusFormat(ctx context.Context, value string) error {

	return o.target.set(ctx, "WindowOptions.SetWindowStatusFormat", "window-status-format", value, false)
}

// UnsetWindowStatusFormat unsets the window-status-format option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetWindowStatusFormat(ctx context.Context) error {
	return o.target.set(ctx, "WindowOptions.UnsetWindowStatusFormat", "window-status-format", "", true)
}

// WindowStatusCurrentFormat observes window-status-current-format; inherited origins may be unavailable.
func (o WindowOptions) WindowStatusCurrentFormat(ctx context.Context) (OptionValue[string], error) {
	return o.target.read(ctx, "WindowOptions.WindowStatusCurrentFormat", "window-status-current-format")
}

// SetWindowStatusCurrentFormat sets the window-status-current-format option in this scope.
func (o WindowOptions) SetWindowStatusCurrentFormat(ctx context.Context, value string) error {

	return o.target.set(ctx, "WindowOptions.SetWindowStatusCurrentFormat", "window-status-current-format", value, false)
}

// UnsetWindowStatusCurrentFormat unsets the window-status-current-format option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetWindowStatusCurrentFormat(ctx context.Context) error {
	return o.target.set(ctx, "WindowOptions.UnsetWindowStatusCurrentFormat", "window-status-current-format", "", true)
}

// AllowPassthrough observes allow-passthrough; inherited origins may be unavailable.
func (o WindowOptions) AllowPassthrough(ctx context.Context) (OptionValue[PassthroughPolicy], error) {

	v, err := o.target.read(ctx, "WindowOptions.AllowPassthrough", "allow-passthrough")
	if err != nil {
		return OptionValue[PassthroughPolicy]{}, err
	}
	r, err := convertOption(v, func(s string) (PassthroughPolicy, error) { return PassthroughPolicy(s), nil })
	if err != nil {
		return OptionValue[PassthroughPolicy]{}, afterError("WindowOptions.AllowPassthrough", err)
	}
	return r, nil

}

// SetAllowPassthrough sets the allow-passthrough option in this scope.
func (o WindowOptions) SetAllowPassthrough(ctx context.Context, value PassthroughPolicy) error {
	if !value.valid() {
		return opError("WindowOptions.SetAllowPassthrough", invalid("enum value"))
	}

	return o.target.set(ctx, "WindowOptions.SetAllowPassthrough", "allow-passthrough", string(value), false)
}

// UnsetAllowPassthrough unsets the allow-passthrough option in this scope, restoring inherited defaults.
func (o WindowOptions) UnsetAllowPassthrough(ctx context.Context) error {
	return o.target.set(ctx, "WindowOptions.UnsetAllowPassthrough", "allow-passthrough", "", true)
}

func nativeOptionScope(name string) (Scope, bool) {
	switch name {
	case "allow-passthrough",
		"allow-rename",
		"allow-set-title",
		"alternate-screen",
		"copy-mode-position-format",
		"cursor-colour",
		"cursor-style",
		"pane-activity",
		"pane-bell",
		"pane-border-format",
		"pane-colours",
		"pane-command-finished",
		"pane-command-started",
		"pane-created",
		"pane-died",
		"pane-exited",
		"pane-focus-in",
		"pane-focus-out",
		"pane-mode-changed",
		"pane-mode-entered",
		"pane-mode-exited",
		"pane-moved",
		"pane-prompt-closed",
		"pane-prompt-opened",
		"pane-resized",
		"pane-scrollbars-style",
		"pane-set-clipboard",
		"pane-shell-prompt",
		"pane-title-changed",
		"remain-on-exit",
		"remain-on-exit-format",
		"scroll-on-clear",
		"switch-mode-match-style",
		"synchronize-panes",
		"tree-mode-preview-format",
		"window-active-style",
		"window-style":
		return ScopePane, true
	case "backspace",
		"buffer-limit",
		"clear-on-attach",
		"codepoint-widths",
		"command-alias",
		"copy-command",
		"dark-theme-black",
		"dark-theme-blue",
		"dark-theme-cyan",
		"dark-theme-dark-grey",
		"dark-theme-green",
		"dark-theme-light-grey",
		"dark-theme-magenta",
		"dark-theme-red",
		"dark-theme-white",
		"dark-theme-yellow",
		"default-client-command",
		"default-terminal",
		"editor",
		"escape-time",
		"exit-empty",
		"exit-unattached",
		"extended-keys",
		"extended-keys-format",
		"focus-events",
		"get-clipboard",
		"history-file",
		"input-buffer-size",
		"light-theme-black",
		"light-theme-blue",
		"light-theme-cyan",
		"light-theme-dark-grey",
		"light-theme-green",
		"light-theme-light-grey",
		"light-theme-magenta",
		"light-theme-red",
		"light-theme-white",
		"light-theme-yellow",
		"message-limit",
		"prefix-timeout",
		"prompt-history-limit",
		"set-clipboard",
		"terminal-features",
		"terminal-overrides",
		"theme",
		"user-keys",
		"variation-selector-always-wide":
		return ScopeServer, true
	case "activity-action",
		"after-bind-key",
		"after-capture-pane",
		"after-copy-mode",
		"after-display-message",
		"after-display-panes",
		"after-kill-pane",
		"after-list-buffers",
		"after-list-clients",
		"after-list-keys",
		"after-list-panes",
		"after-list-sessions",
		"after-list-windows",
		"after-load-buffer",
		"after-lock-server",
		"after-new-session",
		"after-new-window",
		"after-paste-buffer",
		"after-pipe-pane",
		"after-queue",
		"after-refresh-client",
		"after-rename-session",
		"after-rename-window",
		"after-resize-pane",
		"after-resize-window",
		"after-save-buffer",
		"after-select-layout",
		"after-select-pane",
		"after-select-window",
		"after-send-keys",
		"after-set-buffer",
		"after-set-environment",
		"after-set-hook",
		"after-set-option",
		"after-show-environment",
		"after-show-messages",
		"after-show-options",
		"after-split-window",
		"after-unbind-key",
		"alert-activity",
		"alert-bell",
		"alert-silence",
		"assume-paste-time",
		"base-index",
		"bell-action",
		"client-active",
		"client-attached",
		"client-closed",
		"client-created",
		"client-dark-theme",
		"client-detached",
		"client-focus-in",
		"client-focus-out",
		"client-light-theme",
		"client-resized",
		"client-session-changed",
		"command-error",
		"default-command",
		"default-shell",
		"default-size",
		"destroy-unattached",
		"detach-on-destroy",
		"display-time",
		"focus-follows-mouse",
		"history-limit",
		"initial-repeat-time",
		"key-table",
		"lock-after-time",
		"lock-command",
		"marked-pane-changed",
		"message-command-style",
		"message-format",
		"message-line",
		"message-style",
		"mouse",
		"prefix",
		"prefix2",
		"prompt-command-cursor-colour",
		"prompt-command-cursor-style",
		"prompt-cursor-colour",
		"prompt-cursor-style",
		"renumber-windows",
		"repeat-time",
		"session-added-to-group",
		"session-closed",
		"session-created",
		"session-removed-from-group",
		"session-renamed",
		"session-window-changed",
		"set-titles",
		"set-titles-string",
		"silence-action",
		"status",
		"status-bg",
		"status-fg",
		"status-format",
		"status-interval",
		"status-justify",
		"status-keys",
		"status-left",
		"status-left-length",
		"status-left-style",
		"status-position",
		"status-right",
		"status-right-length",
		"status-right-style",
		"status-style",
		"update-environment",
		"visual-activity",
		"visual-bell",
		"visual-silence",
		"window-linked",
		"window-unlinked",
		"word-separators":
		return ScopeSession, true
	case "aggressive-resize",
		"automatic-rename",
		"automatic-rename-format",
		"clock-mode-colour",
		"clock-mode-style",
		"copy-mode-current-line-number-style",
		"copy-mode-current-line-style",
		"copy-mode-current-match-style",
		"copy-mode-line-number-style",
		"copy-mode-line-numbers",
		"copy-mode-mark-style",
		"copy-mode-match-style",
		"copy-mode-position-style",
		"copy-mode-selection-style",
		"display-panes-border-style",
		"display-panes-format",
		"fill-character",
		"main-pane-height",
		"main-pane-width",
		"menu-border-lines",
		"menu-border-style",
		"menu-selected-style",
		"menu-style",
		"mode-keys",
		"mode-style",
		"monitor-activity",
		"monitor-bell",
		"monitor-silence",
		"other-pane-height",
		"other-pane-width",
		"pane-base-index",
		"pane-border-indicators",
		"pane-scrollbars",
		"pane-scrollbars-position",
		"pane-scrollbars-timeout",
		"pane-status-current-style",
		"pane-status-style",
		"popup-border-lines",
		"popup-border-style",
		"popup-style",
		"session-status-current-style",
		"session-status-style",
		"tiled-layout-max-columns",
		"tree-mode-border-style",
		"tree-mode-preview-style",
		"tree-mode-selection-style",
		"window-closed",
		"window-created",
		"window-layout-changed",
		"window-pane-changed",
		"window-pane-current-status-format",
		"window-pane-status-format",
		"window-renamed",
		"window-resized",
		"window-size",
		"window-status-activity-style",
		"window-status-bell-style",
		"window-status-current-format",
		"window-status-current-style",
		"window-status-format",
		"window-status-last-style",
		"window-status-separator",
		"window-status-style",
		"window-unzoomed",
		"window-zoomed",
		"wrap-search",
		"xterm-keys":
		return ScopeWindow, true
	}
	return ScopeServer, false
}
